CREATE TABLE "project_hourly_source_model_stats" (
	"id" text PRIMARY KEY,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"project_id" text NOT NULL,
	"hour_timestamp" timestamp NOT NULL,
	"source" text NOT NULL,
	"used_model" text NOT NULL,
	"used_provider" text NOT NULL,
	"request_count" integer DEFAULT 0 NOT NULL,
	"error_count" integer DEFAULT 0 NOT NULL,
	"cache_count" integer DEFAULT 0 NOT NULL,
	"input_tokens" numeric DEFAULT '0' NOT NULL,
	"output_tokens" numeric DEFAULT '0' NOT NULL,
	"total_tokens" numeric DEFAULT '0' NOT NULL,
	"reasoning_tokens" numeric DEFAULT '0' NOT NULL,
	"cached_tokens" numeric DEFAULT '0' NOT NULL,
	"cache_write_tokens" numeric DEFAULT '0' NOT NULL,
	"cost" real DEFAULT 0 NOT NULL,
	"credits_request_count" integer DEFAULT 0 NOT NULL,
	"api_keys_request_count" integer DEFAULT 0 NOT NULL,
	"credits_cost" real DEFAULT 0 NOT NULL,
	"api_keys_cost" real DEFAULT 0 NOT NULL,
	CONSTRAINT "project_hourly_source_model_stats_bucket_unique" UNIQUE("project_id","hour_timestamp","source","used_model","used_provider")
);
