/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as ProvidersIdRouteImport } from './routes/providers/$id'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as CompareOpenRouterRouteImport } from './routes/compare/open-router'
import { Route as ChangelogSlugRouteImport } from './routes/changelog/$slug'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutUsageRouteImport } from './routes/dashboard/_layout/usage'
import { Route as DashboardLayoutSettingsRouteImport } from './routes/dashboard/_layout/settings'
import { Route as DashboardLayoutProviderKeysRouteImport } from './routes/dashboard/_layout/provider-keys'
import { Route as DashboardLayoutModelsRouteImport } from './routes/dashboard/_layout/models'
import { Route as DashboardLayoutApiKeysRouteImport } from './routes/dashboard/_layout/api-keys'
import { Route as DashboardLayoutActivityRouteImport } from './routes/dashboard/_layout/activity'
import { Route as DashboardLayoutSettingsIndexRouteImport } from './routes/dashboard/_layout/settings/index'
import { Route as DashboardLayoutSettingsTransactionsRouteImport } from './routes/dashboard/_layout/settings/transactions'
import { Route as DashboardLayoutSettingsSecurityRouteImport } from './routes/dashboard/_layout/settings/security'
import { Route as DashboardLayoutSettingsPreferencesRouteImport } from './routes/dashboard/_layout/settings/preferences'
import { Route as DashboardLayoutSettingsPoliciesRouteImport } from './routes/dashboard/_layout/settings/policies'
import { Route as DashboardLayoutSettingsBillingRouteImport } from './routes/dashboard/_layout/settings/billing'
import { Route as DashboardLayoutSettingsAccountRouteImport } from './routes/dashboard/_layout/settings/account'

const DashboardRouteImport = createFileRoute('/dashboard')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)
const CompareOpenRouterRoute = CompareOpenRouterRouteImport.update({
  id: '/compare/open-router',
  path: '/compare/open-router',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutUsageRoute = DashboardLayoutUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutSettingsRoute = DashboardLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutProviderKeysRoute =
  DashboardLayoutProviderKeysRouteImport.update({
    id: '/provider-keys',
    path: '/provider-keys',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutModelsRoute = DashboardLayoutModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutApiKeysRoute = DashboardLayoutApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutActivityRoute = DashboardLayoutActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutSettingsIndexRoute =
  DashboardLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)
const DashboardLayoutSettingsTransactionsRoute =
  DashboardLayoutSettingsTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)
const DashboardLayoutSettingsSecurityRoute =
  DashboardLayoutSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)
const DashboardLayoutSettingsPreferencesRoute =
  DashboardLayoutSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)
const DashboardLayoutSettingsPoliciesRoute =
  DashboardLayoutSettingsPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)
const DashboardLayoutSettingsBillingRoute =
  DashboardLayoutSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)
const DashboardLayoutSettingsAccountRoute =
  DashboardLayoutSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/playground': typeof PlaygroundRoute
  '/signup': typeof SignupRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/compare/open-router': typeof CompareOpenRouterRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/providers/$id': typeof ProvidersIdRoute
  '/changelog': typeof ChangelogIndexRoute
  '/dashboard/activity': typeof DashboardLayoutActivityRoute
  '/dashboard/api-keys': typeof DashboardLayoutApiKeysRoute
  '/dashboard/models': typeof DashboardLayoutModelsRoute
  '/dashboard/provider-keys': typeof DashboardLayoutProviderKeysRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsRouteWithChildren
  '/dashboard/usage': typeof DashboardLayoutUsageRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/settings/account': typeof DashboardLayoutSettingsAccountRoute
  '/dashboard/settings/billing': typeof DashboardLayoutSettingsBillingRoute
  '/dashboard/settings/policies': typeof DashboardLayoutSettingsPoliciesRoute
  '/dashboard/settings/preferences': typeof DashboardLayoutSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardLayoutSettingsSecurityRoute
  '/dashboard/settings/transactions': typeof DashboardLayoutSettingsTransactionsRoute
  '/dashboard/settings/': typeof DashboardLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/playground': typeof PlaygroundRoute
  '/signup': typeof SignupRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/compare/open-router': typeof CompareOpenRouterRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/changelog': typeof ChangelogIndexRoute
  '/dashboard/activity': typeof DashboardLayoutActivityRoute
  '/dashboard/api-keys': typeof DashboardLayoutApiKeysRoute
  '/dashboard/models': typeof DashboardLayoutModelsRoute
  '/dashboard/provider-keys': typeof DashboardLayoutProviderKeysRoute
  '/dashboard/usage': typeof DashboardLayoutUsageRoute
  '/dashboard/settings/account': typeof DashboardLayoutSettingsAccountRoute
  '/dashboard/settings/billing': typeof DashboardLayoutSettingsBillingRoute
  '/dashboard/settings/policies': typeof DashboardLayoutSettingsPoliciesRoute
  '/dashboard/settings/preferences': typeof DashboardLayoutSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardLayoutSettingsSecurityRoute
  '/dashboard/settings/transactions': typeof DashboardLayoutSettingsTransactionsRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/playground': typeof PlaygroundRoute
  '/signup': typeof SignupRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/compare/open-router': typeof CompareOpenRouterRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/providers/$id': typeof ProvidersIdRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/dashboard/_layout/activity': typeof DashboardLayoutActivityRoute
  '/dashboard/_layout/api-keys': typeof DashboardLayoutApiKeysRoute
  '/dashboard/_layout/models': typeof DashboardLayoutModelsRoute
  '/dashboard/_layout/provider-keys': typeof DashboardLayoutProviderKeysRoute
  '/dashboard/_layout/settings': typeof DashboardLayoutSettingsRouteWithChildren
  '/dashboard/_layout/usage': typeof DashboardLayoutUsageRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/_layout/settings/account': typeof DashboardLayoutSettingsAccountRoute
  '/dashboard/_layout/settings/billing': typeof DashboardLayoutSettingsBillingRoute
  '/dashboard/_layout/settings/policies': typeof DashboardLayoutSettingsPoliciesRoute
  '/dashboard/_layout/settings/preferences': typeof DashboardLayoutSettingsPreferencesRoute
  '/dashboard/_layout/settings/security': typeof DashboardLayoutSettingsSecurityRoute
  '/dashboard/_layout/settings/transactions': typeof DashboardLayoutSettingsTransactionsRoute
  '/dashboard/_layout/settings/': typeof DashboardLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/login'
    | '/models'
    | '/onboarding'
    | '/playground'
    | '/signup'
    | '/changelog/$slug'
    | '/compare/open-router'
    | '/dashboard'
    | '/providers/$id'
    | '/changelog'
    | '/dashboard/activity'
    | '/dashboard/api-keys'
    | '/dashboard/models'
    | '/dashboard/provider-keys'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/policies'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings/transactions'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/models'
    | '/onboarding'
    | '/playground'
    | '/signup'
    | '/changelog/$slug'
    | '/compare/open-router'
    | '/dashboard'
    | '/providers/$id'
    | '/changelog'
    | '/dashboard/activity'
    | '/dashboard/api-keys'
    | '/dashboard/models'
    | '/dashboard/provider-keys'
    | '/dashboard/usage'
    | '/dashboard/settings/account'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/policies'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings/transactions'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/login'
    | '/models'
    | '/onboarding'
    | '/playground'
    | '/signup'
    | '/changelog/$slug'
    | '/compare/open-router'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/providers/$id'
    | '/changelog/'
    | '/dashboard/_layout/activity'
    | '/dashboard/_layout/api-keys'
    | '/dashboard/_layout/models'
    | '/dashboard/_layout/provider-keys'
    | '/dashboard/_layout/settings'
    | '/dashboard/_layout/usage'
    | '/dashboard/_layout/'
    | '/dashboard/_layout/settings/account'
    | '/dashboard/_layout/settings/billing'
    | '/dashboard/_layout/settings/policies'
    | '/dashboard/_layout/settings/preferences'
    | '/dashboard/_layout/settings/security'
    | '/dashboard/_layout/settings/transactions'
    | '/dashboard/_layout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  OnboardingRoute: typeof OnboardingRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SignupRoute: typeof SignupRoute
  ChangelogSlugRoute: typeof ChangelogSlugRoute
  CompareOpenRouterRoute: typeof CompareOpenRouterRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ProvidersIdRoute: typeof ProvidersIdRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/compare/open-router': {
      id: '/compare/open-router'
      path: '/compare/open-router'
      fullPath: '/compare/open-router'
      preLoaderRoute: typeof CompareOpenRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/usage': {
      id: '/dashboard/_layout/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardLayoutUsageRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings': {
      id: '/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardLayoutSettingsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/provider-keys': {
      id: '/dashboard/_layout/provider-keys'
      path: '/provider-keys'
      fullPath: '/dashboard/provider-keys'
      preLoaderRoute: typeof DashboardLayoutProviderKeysRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/models': {
      id: '/dashboard/_layout/models'
      path: '/models'
      fullPath: '/dashboard/models'
      preLoaderRoute: typeof DashboardLayoutModelsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/api-keys': {
      id: '/dashboard/_layout/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardLayoutApiKeysRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/activity': {
      id: '/dashboard/_layout/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardLayoutActivityRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings/': {
      id: '/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutSettingsRoute
    }
    '/dashboard/_layout/settings/transactions': {
      id: '/dashboard/_layout/settings/transactions'
      path: '/transactions'
      fullPath: '/dashboard/settings/transactions'
      preLoaderRoute: typeof DashboardLayoutSettingsTransactionsRouteImport
      parentRoute: typeof DashboardLayoutSettingsRoute
    }
    '/dashboard/_layout/settings/security': {
      id: '/dashboard/_layout/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardLayoutSettingsSecurityRouteImport
      parentRoute: typeof DashboardLayoutSettingsRoute
    }
    '/dashboard/_layout/settings/preferences': {
      id: '/dashboard/_layout/settings/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/preferences'
      preLoaderRoute: typeof DashboardLayoutSettingsPreferencesRouteImport
      parentRoute: typeof DashboardLayoutSettingsRoute
    }
    '/dashboard/_layout/settings/policies': {
      id: '/dashboard/_layout/settings/policies'
      path: '/policies'
      fullPath: '/dashboard/settings/policies'
      preLoaderRoute: typeof DashboardLayoutSettingsPoliciesRouteImport
      parentRoute: typeof DashboardLayoutSettingsRoute
    }
    '/dashboard/_layout/settings/billing': {
      id: '/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardLayoutSettingsBillingRouteImport
      parentRoute: typeof DashboardLayoutSettingsRoute
    }
    '/dashboard/_layout/settings/account': {
      id: '/dashboard/_layout/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardLayoutSettingsAccountRouteImport
      parentRoute: typeof DashboardLayoutSettingsRoute
    }
  }
}

interface DashboardLayoutSettingsRouteChildren {
  DashboardLayoutSettingsAccountRoute: typeof DashboardLayoutSettingsAccountRoute
  DashboardLayoutSettingsBillingRoute: typeof DashboardLayoutSettingsBillingRoute
  DashboardLayoutSettingsPoliciesRoute: typeof DashboardLayoutSettingsPoliciesRoute
  DashboardLayoutSettingsPreferencesRoute: typeof DashboardLayoutSettingsPreferencesRoute
  DashboardLayoutSettingsSecurityRoute: typeof DashboardLayoutSettingsSecurityRoute
  DashboardLayoutSettingsTransactionsRoute: typeof DashboardLayoutSettingsTransactionsRoute
  DashboardLayoutSettingsIndexRoute: typeof DashboardLayoutSettingsIndexRoute
}

const DashboardLayoutSettingsRouteChildren: DashboardLayoutSettingsRouteChildren =
  {
    DashboardLayoutSettingsAccountRoute: DashboardLayoutSettingsAccountRoute,
    DashboardLayoutSettingsBillingRoute: DashboardLayoutSettingsBillingRoute,
    DashboardLayoutSettingsPoliciesRoute: DashboardLayoutSettingsPoliciesRoute,
    DashboardLayoutSettingsPreferencesRoute:
      DashboardLayoutSettingsPreferencesRoute,
    DashboardLayoutSettingsSecurityRoute: DashboardLayoutSettingsSecurityRoute,
    DashboardLayoutSettingsTransactionsRoute:
      DashboardLayoutSettingsTransactionsRoute,
    DashboardLayoutSettingsIndexRoute: DashboardLayoutSettingsIndexRoute,
  }

const DashboardLayoutSettingsRouteWithChildren =
  DashboardLayoutSettingsRoute._addFileChildren(
    DashboardLayoutSettingsRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardLayoutActivityRoute: typeof DashboardLayoutActivityRoute
  DashboardLayoutApiKeysRoute: typeof DashboardLayoutApiKeysRoute
  DashboardLayoutModelsRoute: typeof DashboardLayoutModelsRoute
  DashboardLayoutProviderKeysRoute: typeof DashboardLayoutProviderKeysRoute
  DashboardLayoutSettingsRoute: typeof DashboardLayoutSettingsRouteWithChildren
  DashboardLayoutUsageRoute: typeof DashboardLayoutUsageRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutActivityRoute: DashboardLayoutActivityRoute,
  DashboardLayoutApiKeysRoute: DashboardLayoutApiKeysRoute,
  DashboardLayoutModelsRoute: DashboardLayoutModelsRoute,
  DashboardLayoutProviderKeysRoute: DashboardLayoutProviderKeysRoute,
  DashboardLayoutSettingsRoute: DashboardLayoutSettingsRouteWithChildren,
  DashboardLayoutUsageRoute: DashboardLayoutUsageRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  OnboardingRoute: OnboardingRoute,
  PlaygroundRoute: PlaygroundRoute,
  SignupRoute: SignupRoute,
  ChangelogSlugRoute: ChangelogSlugRoute,
  CompareOpenRouterRoute: CompareOpenRouterRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ProvidersIdRoute: ProvidersIdRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
