version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 5
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    cooldown:
      default-days: 5
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      all-dependencies:
        group-by: dependency-name
        patterns:
          - "*"
