import { z } from "@hono/zod-openapi";

export const completionsRequestSchema = z.object({
	model: z.string().openapi({
		example: "gpt-5",
	}),
	messages: z.array(
		z.object({
			role: z.string().openapi({
				example: "user",
			}),
			content: z
				.union([
					z.string().openapi({
						example: "Hello!",
					}),
					z.array(
						z.union([
							z.object({
								type: z.literal("text"),
								text: z.string(),
								cache_control: z
									.object({
										type: z.literal("ephemeral"),
										ttl: z.enum(["5m", "1h"]).optional(),
									})
									.optional(),
							}),
							z.object({
								type: z.literal("image_url"),
								image_url: z.object({
									url: z.string(),
									detail: z.enum(["low", "high", "auto"]).optional(),
								}),
							}),
							z.object({
								type: z.literal("input_audio"),
								input_audio: z.object({
									data: z.string(),
									format: z.enum([
										"wav",
										"mp3",
										"aiff",
										"aac",
										"ogg",
										"flac",
										"m4a",
										"mpeg",
										"mpga",
										"mp4",
										"pcm",
										"webm",
									]),
								}),
							}),
							z.object({
								type: z.literal("file"),
								file: z
									.object({
										filename: z.string().optional(),
										file_data: z.string().optional().openapi({
											description:
												"Base64-encoded data URL with MIME prefix, e.g. 'data:application/pdf;base64,<data>'.",
										}),
										file_id: z.string().optional().openapi({
											description:
												"Reference to a file uploaded via the provider's Files API.",
										}),
									})
									.refine((file) => Boolean(file.file_data || file.file_id), {
										message:
											"file.file_data or file.file_id is required for file content",
									}),
							}),
						]),
					),
				])
				.nullable()
				.optional(),
			name: z.string().optional(),
			tool_call_id: z.string().optional(),
			tool_calls: z
				.array(
					z.object({
						id: z.string(),
						type: z.literal("function"),
						function: z.object({
							name: z.string(),
							arguments: z.string(),
						}),
					}),
				)
				.optional()
				.openapi({
					description:
						"A list of tool calls generated by the model in this message.",
					example: [
						{
							id: "call_abc123",
							type: "function",
							function: {
								name: "get_current_weather",
								arguments: '{"location": "Boston, MA"}',
							},
						},
					],
				}),
			reasoning: z.string().optional(),
			reasoning_content: z.string().optional(),
			reasoning_details: z
				.array(
					z
						.object({
							text: z.string().optional(),
							type: z.string().optional(),
						})
						.passthrough(),
				)
				.optional(),
		}),
	),
	temperature: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 0.7,
		}),
	max_tokens: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 1000,
		}),
	top_p: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 0.9,
		}),
	frequency_penalty: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 0.0,
		}),
	presence_penalty: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 0.0,
		}),
	response_format: z
		.union([
			z.object({
				type: z.enum(["text", "json_object"]).openapi({
					example: "json_object",
				}),
			}),
			z.object({
				type: z.literal("json_schema"),
				json_schema: z.object({
					name: z.string(),
					description: z.string().optional(),
					schema: z.record(z.any()),
					strict: z.boolean().optional(),
				}),
			}),
		])
		.optional(),
	stream: z.boolean().optional().default(false),
	n: z
		.number()
		.int()
		.min(1)
		.max(128)
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"How many chat completion choices to generate for each input message. Only accepted when the resolved model supports it upstream (currently OpenAI Chat Completions models and Google Gemini 2.5 models via `candidateCount`); requests for unsupported models are rejected with 400. Streaming is supported for OpenAI models: choice deltas are demultiplexed by `choices[].index` on a single SSE stream. Exceptions rejected with 400: `n > 1` with `stream: true` **and** function `tools` (the streaming tool-call aggregator can't disambiguate concurrent calls across choices; native `web_search` tools and the `web_search: true` flag are exempt), `n > 1` with `stream: true` on Google models (Gemini rejects candidateCount on streamGenerateContent), and `n > 8` on Google models (Gemini caps candidateCount at 8).",
			example: 1,
		}),
	prompt_cache_key: z
		.string()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"OpenAI prompt caching key used to improve cache routing for requests with shared prompt prefixes.",
			example: "tenant-123",
		}),
	prompt_cache_retention: z
		.enum(["in_memory", "24h"])
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"OpenAI prompt cache retention policy. OpenAI supports in_memory and 24h for eligible models.",
			example: "24h",
		}),
	user: z
		.string()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"OpenAI end-user identifier. Used as a fallback sticky-routing session key when no x-session-id header or prompt_cache_key is provided.",
			example: "user-123",
		}),
	tools: z
		.array(
			z.union([
				z.object({
					type: z.literal("function"),
					function: z.object({
						name: z.string(),
						description: z.string().optional(),
						parameters: z.record(z.any()).optional(),
					}),
				}),
				z.object({
					type: z.literal("web_search"),
					user_location: z
						.object({
							city: z.string().optional(),
							region: z.string().optional(),
							country: z.string().optional(),
							timezone: z.string().optional(),
						})
						.optional(),
					search_context_size: z.enum(["low", "medium", "high"]).optional(),
					max_uses: z.number().optional(),
				}),
			]),
		)
		.optional(),
	tool_choice: z
		.union([
			z.literal("auto"),
			z.literal("none"),
			z.literal("required"),
			z.object({
				type: z.literal("function"),
				function: z.object({
					name: z.string(),
				}),
			}),
		])
		.optional(),
	reasoning_effort: z
		.enum(["none", "minimal", "low", "medium", "high", "xhigh", "max"])
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"Controls the reasoning effort for reasoning-capable models. `none` is only supported by OpenAI's newer reasoning models (e.g. gpt-5.4 and later); for other providers it disables reasoning. `max` is the highest tier and is honored natively by Anthropic models (above `xhigh`); providers without a `max` tier treat it as `high`.",
			example: "medium",
		}),
	reasoning: z
		.object({
			effort: z
				.enum(["none", "minimal", "low", "medium", "high", "xhigh", "max"])
				.optional()
				.openapi({
					description:
						"Controls the reasoning effort. Alternative to top-level reasoning_effort. Cannot be used together with reasoning_effort. `max` is the highest tier (honored natively by Anthropic, above `xhigh`); providers without a `max` tier treat it as `high`.",
					example: "medium",
				}),
			max_tokens: z.number().int().positive().optional().openapi({
				description:
					"Exact number of tokens to allocate for reasoning. When specified, overrides effort. Supported by Anthropic and Google thinking models.",
				example: 4000,
			}),
		})
		.optional()
		.openapi({
			description:
				"Unified reasoning configuration object for controlling reasoning behavior",
		}),
	effort: z
		.enum(["low", "medium", "high"])
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"Controls the computational effort for supported models (currently only claude-opus-4-5-20251101)",
			example: "medium",
		}),
	service_tier: z
		.enum(["auto", "default", "flex", "priority"])
		.optional()
		.openapi({
			description:
				"Processing tier for the request. `flex` and `priority` are forwarded only for provider/model mappings that explicitly support the requested tier, such as supported OpenAI and Google mappings. `auto`/`default` use the standard on-demand tier. Unsupported tier requests return a 400 `unsupported_service_tier` error.",
			example: "flex",
		}),
	routing: z
		.enum(["auto", "price", "throughput", "latency"])
		.optional()
		.openapi({
			description:
				"Provider selection strategy for model-id routing, named after the factor it optimizes. `auto` (default) uses the full weighted smart-routing score. `price`, `throughput`, and `latency` each give a 90% relative weight to that factor while keeping a small uptime weight so requests still fall back to other providers when the top pick has extremely bad uptime. `latency` only biases streaming requests. Combining `routing` with a specific provider prefix (e.g. `openai/gpt-4o`) returns a 400. On coding (dev) plans only `auto` and `price` are allowed.",
			example: "price",
		}),
	free_models_only: z.boolean().optional().default(false).openapi({
		description:
			"When used with auto routing, only route to free models (models with zero input and output pricing)",
		example: false,
	}),
	onboarding: z.boolean().optional().default(false).openapi({
		description:
			"When true, skips email verification for free model usage. Intended for onboarding flows.",
		example: false,
	}),
	no_reasoning: z.boolean().optional().default(false).openapi({
		description:
			"When used with auto routing, exclude reasoning models from selection",
		example: false,
	}),
	// Z.ai specific parameter - not documented in OpenAPI
	sensitive_word_check: z
		.object({
			status: z.enum(["DISABLE", "ENABLE"]),
		})
		.optional(),
	// Image generation config (Google and Alibaba)
	image_config: z
		.object({
			aspect_ratio: z.string().optional(),
			image_size: z.string().optional(),
			image_quality: z.enum(["low", "medium", "high", "auto"]).optional(),
			n: z.number().optional(),
			seed: z.number().optional(),
		})
		.optional(),
	// Web search enablement
	web_search: z.boolean().optional().default(false).openapi({
		description:
			"Enable native web search for models that support it. When enabled, the model can search the web for real-time information.",
		example: true,
	}),
	// Plugins configuration
	plugins: z
		.array(
			z.object({
				id: z.enum(["response-healing"]).openapi({
					description: "Plugin identifier",
					example: "response-healing",
				}),
			}),
		)
		.optional()
		.openapi({
			description:
				"Plugins to enable for this request. Currently supported: response-healing (automatically repairs malformed JSON responses when using response_format)",
			example: [{ id: "response-healing" }],
		}),
});

export type CompletionsRequest = z.infer<typeof completionsRequestSchema>;
