import { z } from "@hono/zod-openapi";

const googleExtraContentSchema = z.object({
	google: z.object({ thought_signature: z.string().optional() }).optional(),
});

export const reasoningDetailsSchema = z.array(
	z
		.object({ text: z.string().optional(), type: z.string().optional() })
		.passthrough(),
);

export const completionsRequestSchema = z.object({
	model: z.string().openapi({
		example: "gpt-5",
	}),
	messages: z.array(
		z.object({
			role: z
				.enum(["developer", "system", "user", "assistant", "tool", "function"])
				.openapi({
					example: "user",
				}),
			content: z
				.union([
					z.string().openapi({
						example: "Hello!",
					}),
					z.array(
						z.union([
							z.object({
								type: z.literal("text"),
								text: z.string(),
								extra_content: googleExtraContentSchema.optional(),
								cache_control: z
									.object({
										type: z.literal("ephemeral"),
										ttl: z.enum(["5m", "1h"]).optional(),
									})
									.optional(),
								prompt_cache_breakpoint: z
									.object({
										mode: z.enum(["explicit"]).optional(),
									})
									.optional()
									.openapi({
										description:
											"OpenAI explicit prompt cache breakpoint marker (GPT-5.6 and later). Ends a cacheable prefix when the request sets prompt_cache_options.mode to 'explicit'. Stripped for providers/models without explicit prompt caching support.",
									}),
							}),
							z.object({
								type: z.literal("image_url"),
								image_url: z.object({
									url: z.string(),
									detail: z.enum(["low", "high", "auto"]).optional(),
								}),
								prompt_cache_breakpoint: z
									.object({
										mode: z.enum(["explicit"]).optional(),
									})
									.optional(),
							}),
							z.object({
								type: z.literal("input_audio"),
								input_audio: z.object({
									data: z.string(),
									format: z.enum([
										"wav",
										"mp3",
										"aiff",
										"aac",
										"ogg",
										"flac",
										"m4a",
										"mpeg",
										"mpga",
										"mp4",
										"pcm",
										"webm",
									]),
								}),
								prompt_cache_breakpoint: z
									.object({
										mode: z.enum(["explicit"]).optional(),
									})
									.optional(),
							}),
							z.object({
								type: z.literal("file"),
								file: z
									.object({
										filename: z.string().optional(),
										file_data: z.string().optional().openapi({
											description:
												"Base64-encoded data URL with MIME prefix, e.g. 'data:application/pdf;base64,<data>'.",
										}),
										file_id: z.string().optional().openapi({
											description:
												"Reference to a file uploaded via the provider's Files API.",
										}),
									})
									.refine((file) => Boolean(file.file_data || file.file_id), {
										message:
											"file.file_data or file.file_id is required for file content",
									}),
								prompt_cache_breakpoint: z
									.object({
										mode: z.enum(["explicit"]).optional(),
									})
									.optional(),
							}),
						]),
					),
				])
				.nullable()
				.optional(),
			name: z.string().optional(),
			tool_call_id: z.string().optional(),
			tool_calls: z
				.array(
					z.object({
						id: z.string(),
						type: z.literal("function"),
						extra_content: googleExtraContentSchema.optional(),
						function: z.object({
							name: z.string(),
							arguments: z.string(),
						}),
					}),
				)
				.optional()
				.openapi({
					description:
						"A list of tool calls generated by the model in this message.",
					example: [
						{
							id: "call_abc123",
							type: "function",
							function: {
								name: "get_current_weather",
								arguments: '{"location": "Boston, MA"}',
							},
						},
					],
				}),
			reasoning: z.string().optional(),
			reasoning_content: z.string().optional(),
			reasoning_details: reasoningDetailsSchema.optional(),
			phase: z.enum(["commentary", "final_answer"]).optional().openapi({
				description:
					"OpenAI Responses assistant-message phase. Replayed upstream for OpenAI Responses API models; stripped for other providers.",
			}),
			content_before_tool_calls: z.boolean().optional().openapi({
				description:
					"Marks assistant content that preceded the message's tool calls (pre-tool commentary on OpenAI Responses API models), so replay preserves the original item order. Stripped for other providers.",
			}),
			message_items: z
				.array(
					z.object({
						text: z.string(),
						phase: z.enum(["commentary", "final_answer"]).optional(),
						preceding_tool_calls: z.number().int().nonnegative().optional(),
					}),
				)
				.optional()
				.openapi({
					description:
						"Separate phased assistant message items (e.g. commentary and final_answer) emitted by OpenAI Responses API models in a single turn. preceding_tool_calls records how many of the message's tool calls came before each item. Replayed upstream as individual message items in their original order; stripped for other providers.",
				}),
			anthropic_native_blocks: z
				.array(z.object({ type: z.string() }).passthrough())
				.optional()
				.openapi({
					description:
						"Anthropic content blocks with no OpenAI-format equivalent. On an assistant message these are the server-side tool search blocks (`server_tool_use` + `tool_search_tool_result`), replayed ahead of the message's tool calls; on a tool message they are the `tool_result` content array, which is how a client-side tool search returns `tool_reference` blocks. Replayed on the Anthropic Messages API only and stripped for every other provider.",
				}),
			tool_result_cache_control: z
				.object({
					type: z.enum(["ephemeral"]),
					ttl: z.enum(["5m", "1h"]).optional(),
				})
				.optional()
				.openapi({
					description:
						"Prompt-cache breakpoint for the Anthropic `tool_result` block this tool message becomes. The OpenAI tool message shape has nowhere to carry it, so it rides here. Applied on the Anthropic Messages API only and stripped for every other provider.",
				}),
		}),
	),
	temperature: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 0.7,
		}),
	max_tokens: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 1000,
		}),
	top_p: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 0.9,
		}),
	frequency_penalty: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 0.0,
		}),
	presence_penalty: z
		.number()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			example: 0.0,
		}),
	response_format: z
		.union([
			z.object({
				type: z.enum(["text", "json_object"]).openapi({
					example: "json_object",
				}),
			}),
			z.object({
				type: z.literal("json_schema"),
				json_schema: z.object({
					name: z.string(),
					description: z.string().optional(),
					schema: z.record(z.any()),
					strict: z.boolean().optional(),
				}),
			}),
		])
		.optional(),
	stream: z.boolean().optional().default(false),
	n: z
		.number()
		.int()
		.min(1)
		.max(128)
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"How many chat completion choices to generate for each input message. Only accepted when the resolved model supports it upstream (currently OpenAI Chat Completions models and Google Gemini 2.5 models via `candidateCount`); requests for unsupported models are rejected with 400. Streaming is supported for OpenAI models: choice deltas are demultiplexed by `choices[].index` on a single SSE stream. Exceptions rejected with 400: `n > 1` with `stream: true` **and** function `tools` (the streaming tool-call aggregator can't disambiguate concurrent calls across choices; native `web_search` tools and the `web_search: true` flag are exempt), `n > 1` with `stream: true` on Google models (Gemini rejects candidateCount on streamGenerateContent), and `n > 8` on Google models (Gemini caps candidateCount at 8).",
			example: 1,
		}),
	prompt_cache_key: z
		.string()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"OpenAI prompt caching key used to improve cache routing for requests with shared prompt prefixes.",
			example: "tenant-123",
		}),
	prompt_cache_retention: z
		.enum(["in_memory", "24h"])
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"OpenAI prompt cache retention policy. OpenAI supports in_memory and 24h for eligible models.",
			example: "24h",
		}),
	prompt_cache_options: z
		.object({
			mode: z.enum(["implicit", "explicit"]).optional(),
			ttl: z.enum(["30m"]).optional(),
		})
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"OpenAI explicit prompt caching options (GPT-5.6 and later). mode 'implicit' (default) places an automatic cache breakpoint at the latest message; 'explicit' caches only content parts marked with prompt_cache_breakpoint. Only forwarded for OpenAI models that support explicit prompt caching.",
			example: { mode: "explicit" },
		}),
	user: z
		.string()
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"OpenAI end-user identifier. Used as a fallback sticky-routing session key when no x-session-id header or prompt_cache_key is provided.",
			example: "user-123",
		}),
	tools: z
		.array(
			z.union([
				z.object({
					type: z.literal("function"),
					function: z.object({
						name: z.string(),
						description: z.string().optional(),
						parameters: z.record(z.any()).optional(),
					}),
					defer_loading: z.boolean().optional().openapi({
						description:
							"Anthropic only. Keeps the tool out of the rendered tools section so it never enters the cached prompt prefix, and loads it on demand once the tool search tool discovers it. Requires a `tool_search` tool in `tools`, and Anthropic rejects a request whose tools are all deferred. Stripped for every other provider, which receives the tool eagerly instead.",
					}),
					cache_control: z
						.object({
							type: z.enum(["ephemeral"]),
							ttl: z.enum(["5m", "1h"]).optional(),
						})
						.optional()
						.openapi({
							description:
								"Anthropic only. Cache breakpoint ending the tool-definitions prefix, which Anthropic renders before the system prompt and messages. Placed on the last tool it caches every tool up to and including that one, and counts toward Anthropic's limit of 4 breakpoints per request. Stripped for every other provider.",
						}),
				}),
				z.object({
					type: z.literal("tool_search"),
					tool_search_type: z
						.string()
						.regex(/^tool_search_tool/)
						.openapi({
							description:
								"Anthropic tool search tool type, e.g. `tool_search_tool_regex_20251119` or `tool_search_tool_bm25_20251119`.",
						}),
					name: z.string().optional(),
				}),
				z.object({
					type: z.literal("web_search"),
					user_location: z
						.object({
							city: z.string().optional(),
							region: z.string().optional(),
							country: z.string().optional(),
							timezone: z.string().optional(),
						})
						.optional(),
					search_context_size: z.enum(["low", "medium", "high"]).optional(),
					max_uses: z.number().optional(),
					allowed_domains: z.array(z.string()).optional(),
					blocked_domains: z.array(z.string()).optional(),
				}),
			]),
		)
		.optional(),
	tool_choice: z
		.union([
			z.literal("auto"),
			z.literal("none"),
			z.literal("required"),
			z.object({
				type: z.literal("function"),
				function: z.object({
					name: z.string(),
				}),
			}),
			z.object({
				type: z.literal("web_search"),
			}),
		])
		.optional()
		.openapi({
			description:
				'Controls which tool the model calls. `{"type": "web_search"}` demands a search instead of offering one, and requires a `web_search` tool in `tools`. Providers whose web search is model-elected are unaffected by it — the model already decides — but it is the only way to reach providers that can search solely on demand (currently Alibaba\'s DashScope and its resellers), which are otherwise skipped when routing a web search request.',
		}),
	reasoning_effort: z
		.enum(["none", "minimal", "low", "medium", "high", "xhigh", "max"])
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"Controls the reasoning effort for reasoning-capable models. `none` is only supported by OpenAI's newer reasoning models (e.g. gpt-5.4 and later); for other providers it disables reasoning. `max` is the highest tier (above `xhigh`), supported by Anthropic models and OpenAI GPT-5.6 models. The gateway never downgrades effort tiers: providers that accept an effort parameter receive the value unchanged (an unsupported value results in a provider error), while providers that take a thinking budget instead (e.g. Anthropic, Google) translate each tier to a native budget. The exact values each provider mapping accepts are exposed as `reasoning_efforts` on `/v1/models`.",
			example: "medium",
		}),
	reasoning: z
		.object({
			effort: z
				.enum(["none", "minimal", "low", "medium", "high", "xhigh", "max"])
				.optional()
				.openapi({
					description:
						"Controls the reasoning effort. Alternative to top-level reasoning_effort. Cannot be used together with reasoning_effort. `max` is the highest tier (above `xhigh`), supported by Anthropic models and OpenAI GPT-5.6 models. Tiers are never downgraded by the gateway: enum-based providers receive the value unchanged (unsupported values result in a provider error), while budget-based providers (e.g. Anthropic, Google) translate the tier to a native thinking budget. See `reasoning_efforts` on `/v1/models` for the values each mapping accepts.",
					example: "medium",
				}),
			max_tokens: z.number().int().positive().optional().openapi({
				description:
					"Exact number of tokens to allocate for reasoning. When specified, overrides effort. Supported by Anthropic and Google thinking models.",
				example: 4000,
			}),
			context: z
				.enum(["auto", "current_turn", "all_turns"])
				.optional()
				.openapi({
					description:
						"How much replayed reasoning the model considers (OpenAI Responses API models only). Omitting the field is equivalent to 'auto'. Forwarded upstream as reasoning.context; ignored by other providers.",
					example: "current_turn",
				}),
		})
		.optional()
		.openapi({
			description:
				"Unified reasoning configuration object for controlling reasoning behavior",
		}),
	effort: z
		.enum(["low", "medium", "high"])
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"Controls the computational effort for supported models (currently only claude-opus-4-5-20251101)",
			example: "medium",
		}),
	verbosity: z
		.enum(["low", "medium", "high"])
		.nullable()
		.optional()
		.transform((val) => (val === null ? undefined : val))
		.openapi({
			description:
				"Controls how detailed the model's responses are. Only supported by OpenAI GPT-5 and later models; requests to models without verbosity support return a 400 error.",
			example: "low",
		}),
	service_tier: z
		.enum(["auto", "default", "flex", "priority"])
		.optional()
		.openapi({
			description:
				"Processing tier for the request. `flex` and `priority` are forwarded only for provider/model mappings that explicitly support the requested tier, such as supported OpenAI and Google mappings. `auto`/`default` use the standard on-demand tier. Unsupported tier requests return a 400 `unsupported_service_tier` error. On coding (dev) plans only `auto`, `default` and `flex` are allowed.",
			example: "flex",
		}),
	routing: z
		.enum(["auto", "price", "throughput", "latency"])
		.optional()
		.openapi({
			description:
				"Provider selection strategy for model-id routing, named after the factor it optimizes. `auto` (default) uses the full weighted smart-routing score. `price`, `throughput`, and `latency` each give a 90% relative weight to that factor while keeping a small uptime weight so requests still fall back to other providers when the top pick has extremely bad uptime. `latency` only biases streaming requests. Combining `routing` with a specific provider prefix (e.g. `openai/gpt-4o`) returns a 400. On coding (dev) plans only `auto` and `price` are allowed.",
			example: "price",
		}),
	free_models_only: z.boolean().optional().default(false).openapi({
		description:
			"When used with auto routing, only route to free models (models with zero input and output pricing)",
		example: false,
	}),
	onboarding: z.boolean().optional().default(false).openapi({
		description:
			"Deprecated and ignored. This once skipped email verification for free model usage, but the flag is client-supplied, so any account could assert it. Onboarding is now recognized server-side by the API proxy; setting this grants nothing.",
		deprecated: true,
		example: false,
	}),
	no_reasoning: z.boolean().optional().default(false).openapi({
		description:
			"When used with auto routing, exclude reasoning models from selection",
		example: false,
	}),
	// Z.ai specific parameter - not documented in OpenAPI
	sensitive_word_check: z
		.object({
			status: z.enum(["DISABLE", "ENABLE"]),
		})
		.optional(),
	// Image generation config (Google and Alibaba)
	image_config: z
		.object({
			aspect_ratio: z.string().optional(),
			image_size: z.string().optional(),
			image_quality: z.enum(["low", "medium", "high", "auto"]).optional(),
			n: z.number().optional(),
			seed: z.number().optional(),
		})
		.optional(),
	// Web search enablement
	web_search: z.boolean().optional().default(false).openapi({
		description:
			"Enable native web search for models that support it. When enabled, the model can search the web for real-time information.",
		example: true,
	}),
	// Plugins configuration
	plugins: z
		.array(
			z.object({
				id: z.enum(["response-healing"]).openapi({
					description: "Plugin identifier",
					example: "response-healing",
				}),
			}),
		)
		.optional()
		.openapi({
			description:
				"Plugins to enable for this request. Currently supported: response-healing (automatically repairs malformed JSON responses when using response_format)",
			example: [{ id: "response-healing" }],
		}),
});

export type CompletionsRequest = z.infer<typeof completionsRequestSchema>;
