CREATE TABLE "global_aggregation_state" (
	"id" text PRIMARY KEY DEFAULT 'singleton',
	"last_processed_hour" timestamp,
	"last_safety_net_day" timestamp,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "global_model_stats" (
	"id" text PRIMARY KEY,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"day_timestamp" timestamp NOT NULL,
	"used_model" text NOT NULL,
	"used_provider" text NOT NULL,
	"request_count" integer DEFAULT 0 NOT NULL,
	"error_count" integer DEFAULT 0 NOT NULL,
	"cache_count" integer DEFAULT 0 NOT NULL,
	"streamed_count" integer DEFAULT 0 NOT NULL,
	"non_streamed_count" integer DEFAULT 0 NOT NULL,
	"completed_count" integer DEFAULT 0 NOT NULL,
	"length_limit_count" integer DEFAULT 0 NOT NULL,
	"content_filter_count" integer DEFAULT 0 NOT NULL,
	"tool_calls_count" integer DEFAULT 0 NOT NULL,
	"canceled_count" integer DEFAULT 0 NOT NULL,
	"unknown_finish_count" integer DEFAULT 0 NOT NULL,
	"client_error_count" integer DEFAULT 0 NOT NULL,
	"gateway_error_count" integer DEFAULT 0 NOT NULL,
	"upstream_error_count" integer DEFAULT 0 NOT NULL,
	"input_tokens" numeric DEFAULT '0' NOT NULL,
	"output_tokens" numeric DEFAULT '0' NOT NULL,
	"total_tokens" numeric DEFAULT '0' NOT NULL,
	"reasoning_tokens" numeric DEFAULT '0' NOT NULL,
	"cached_tokens" numeric DEFAULT '0' NOT NULL,
	"cache_write_tokens" numeric DEFAULT '0' NOT NULL,
	"cost" real DEFAULT 0 NOT NULL,
	"input_cost" real DEFAULT 0 NOT NULL,
	"output_cost" real DEFAULT 0 NOT NULL,
	"request_cost" real DEFAULT 0 NOT NULL,
	"data_storage_cost" real DEFAULT 0 NOT NULL,
	"discount_savings" real DEFAULT 0 NOT NULL,
	"image_input_cost" real DEFAULT 0 NOT NULL,
	"image_output_cost" real DEFAULT 0 NOT NULL,
	"video_output_cost" real DEFAULT 0 NOT NULL,
	"cached_input_cost" real DEFAULT 0 NOT NULL,
	"cache_write_input_cost" real DEFAULT 0 NOT NULL,
	"credits_request_count" integer DEFAULT 0 NOT NULL,
	"api_keys_request_count" integer DEFAULT 0 NOT NULL,
	"credits_cost" real DEFAULT 0 NOT NULL,
	"api_keys_cost" real DEFAULT 0 NOT NULL,
	"credits_data_storage_cost" real DEFAULT 0 NOT NULL,
	"api_keys_data_storage_cost" real DEFAULT 0 NOT NULL,
	CONSTRAINT "global_model_stats_day_timestamp_used_model_used_provider_unique" UNIQUE("day_timestamp","used_model","used_provider")
);
--> statement-breakpoint
CREATE TABLE "global_source_stats" (
	"id" text PRIMARY KEY,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"day_timestamp" timestamp NOT NULL,
	"source" text NOT NULL,
	"request_count" integer DEFAULT 0 NOT NULL,
	"error_count" integer DEFAULT 0 NOT NULL,
	"cache_count" integer DEFAULT 0 NOT NULL,
	"streamed_count" integer DEFAULT 0 NOT NULL,
	"non_streamed_count" integer DEFAULT 0 NOT NULL,
	"completed_count" integer DEFAULT 0 NOT NULL,
	"length_limit_count" integer DEFAULT 0 NOT NULL,
	"content_filter_count" integer DEFAULT 0 NOT NULL,
	"tool_calls_count" integer DEFAULT 0 NOT NULL,
	"canceled_count" integer DEFAULT 0 NOT NULL,
	"unknown_finish_count" integer DEFAULT 0 NOT NULL,
	"client_error_count" integer DEFAULT 0 NOT NULL,
	"gateway_error_count" integer DEFAULT 0 NOT NULL,
	"upstream_error_count" integer DEFAULT 0 NOT NULL,
	"input_tokens" numeric DEFAULT '0' NOT NULL,
	"output_tokens" numeric DEFAULT '0' NOT NULL,
	"total_tokens" numeric DEFAULT '0' NOT NULL,
	"reasoning_tokens" numeric DEFAULT '0' NOT NULL,
	"cached_tokens" numeric DEFAULT '0' NOT NULL,
	"cache_write_tokens" numeric DEFAULT '0' NOT NULL,
	"cost" real DEFAULT 0 NOT NULL,
	"input_cost" real DEFAULT 0 NOT NULL,
	"output_cost" real DEFAULT 0 NOT NULL,
	"request_cost" real DEFAULT 0 NOT NULL,
	"data_storage_cost" real DEFAULT 0 NOT NULL,
	"discount_savings" real DEFAULT 0 NOT NULL,
	"image_input_cost" real DEFAULT 0 NOT NULL,
	"image_output_cost" real DEFAULT 0 NOT NULL,
	"video_output_cost" real DEFAULT 0 NOT NULL,
	"cached_input_cost" real DEFAULT 0 NOT NULL,
	"cache_write_input_cost" real DEFAULT 0 NOT NULL,
	"credits_request_count" integer DEFAULT 0 NOT NULL,
	"api_keys_request_count" integer DEFAULT 0 NOT NULL,
	"credits_cost" real DEFAULT 0 NOT NULL,
	"api_keys_cost" real DEFAULT 0 NOT NULL,
	"credits_data_storage_cost" real DEFAULT 0 NOT NULL,
	"api_keys_data_storage_cost" real DEFAULT 0 NOT NULL,
	CONSTRAINT "global_source_stats_day_timestamp_source_unique" UNIQUE("day_timestamp","source")
);
--> statement-breakpoint
CREATE INDEX "global_model_stats_day_timestamp_idx" ON "global_model_stats" ("day_timestamp");--> statement-breakpoint
CREATE INDEX "global_model_stats_used_model_day_timestamp_idx" ON "global_model_stats" ("used_model","day_timestamp");--> statement-breakpoint
CREATE INDEX "global_model_stats_p_m_time_idx" ON "global_model_stats" ("used_provider","used_model","day_timestamp");--> statement-breakpoint
CREATE INDEX "global_source_stats_day_timestamp_idx" ON "global_source_stats" ("day_timestamp");--> statement-breakpoint
CREATE INDEX "global_source_stats_source_day_timestamp_idx" ON "global_source_stats" ("source","day_timestamp");