CREATE TABLE "project_hourly_source_stats" (
	"id" text PRIMARY KEY,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"project_id" text NOT NULL,
	"hour_timestamp" timestamp NOT NULL,
	"source" text NOT NULL,
	"request_count" integer DEFAULT 0 NOT NULL,
	"error_count" integer DEFAULT 0 NOT NULL,
	"cache_count" integer DEFAULT 0 NOT NULL,
	"streamed_count" integer DEFAULT 0 NOT NULL,
	"non_streamed_count" integer DEFAULT 0 NOT NULL,
	"completed_count" integer DEFAULT 0 NOT NULL,
	"length_limit_count" integer DEFAULT 0 NOT NULL,
	"content_filter_count" integer DEFAULT 0 NOT NULL,
	"tool_calls_count" integer DEFAULT 0 NOT NULL,
	"canceled_count" integer DEFAULT 0 NOT NULL,
	"unknown_finish_count" integer DEFAULT 0 NOT NULL,
	"client_error_count" integer DEFAULT 0 NOT NULL,
	"gateway_error_count" integer DEFAULT 0 NOT NULL,
	"upstream_error_count" integer DEFAULT 0 NOT NULL,
	"input_tokens" numeric DEFAULT '0' NOT NULL,
	"output_tokens" numeric DEFAULT '0' NOT NULL,
	"total_tokens" numeric DEFAULT '0' NOT NULL,
	"reasoning_tokens" numeric DEFAULT '0' NOT NULL,
	"cached_tokens" numeric DEFAULT '0' NOT NULL,
	"cache_write_tokens" numeric DEFAULT '0' NOT NULL,
	"cost" real DEFAULT 0 NOT NULL,
	"input_cost" real DEFAULT 0 NOT NULL,
	"output_cost" real DEFAULT 0 NOT NULL,
	"request_cost" real DEFAULT 0 NOT NULL,
	"data_storage_cost" real DEFAULT 0 NOT NULL,
	"discount_savings" real DEFAULT 0 NOT NULL,
	"image_input_cost" real DEFAULT 0 NOT NULL,
	"image_output_cost" real DEFAULT 0 NOT NULL,
	"audio_input_cost" real DEFAULT 0 NOT NULL,
	"video_output_cost" real DEFAULT 0 NOT NULL,
	"cached_input_cost" real DEFAULT 0 NOT NULL,
	"cache_write_input_cost" real DEFAULT 0 NOT NULL,
	"credits_request_count" integer DEFAULT 0 NOT NULL,
	"api_keys_request_count" integer DEFAULT 0 NOT NULL,
	"credits_cost" real DEFAULT 0 NOT NULL,
	"api_keys_cost" real DEFAULT 0 NOT NULL,
	"credits_data_storage_cost" real DEFAULT 0 NOT NULL,
	"api_keys_data_storage_cost" real DEFAULT 0 NOT NULL,
	CONSTRAINT "project_hourly_source_stats_project_id_hour_timestamp_source_unique" UNIQUE("project_id","hour_timestamp","source")
);
--> statement-breakpoint
CREATE INDEX "project_hourly_source_stats_project_id_hour_timestamp_idx" ON "project_hourly_source_stats" ("project_id","hour_timestamp");--> statement-breakpoint
CREATE INDEX "project_hourly_source_stats_hour_timestamp_idx" ON "project_hourly_source_stats" ("hour_timestamp");--> statement-breakpoint
CREATE INDEX "project_hourly_source_stats_source_hour_timestamp_idx" ON "project_hourly_source_stats" ("source","hour_timestamp");