CREATE TABLE "model_provider_mapping_usage_history" (
	"id" text PRIMARY KEY,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"model_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"model_provider_mapping_id" text NOT NULL,
	"used_mode" text NOT NULL,
	"minute_timestamp" timestamp NOT NULL,
	"logs_count" integer DEFAULT 0 NOT NULL,
	"errors_count" integer DEFAULT 0 NOT NULL,
	"client_errors_count" integer DEFAULT 0 NOT NULL,
	"gateway_errors_count" integer DEFAULT 0 NOT NULL,
	"upstream_errors_count" integer DEFAULT 0 NOT NULL,
	"completed_count" integer DEFAULT 0 NOT NULL,
	"length_limit_count" integer DEFAULT 0 NOT NULL,
	"content_filter_count" integer DEFAULT 0 NOT NULL,
	"tool_calls_count" integer DEFAULT 0 NOT NULL,
	"canceled_count" integer DEFAULT 0 NOT NULL,
	"unknown_finish_count" integer DEFAULT 0 NOT NULL,
	"cached_count" integer DEFAULT 0 NOT NULL,
	"total_input_tokens" integer DEFAULT 0 NOT NULL,
	"total_output_tokens" integer DEFAULT 0 NOT NULL,
	"total_tokens" integer DEFAULT 0 NOT NULL,
	"total_reasoning_tokens" integer DEFAULT 0 NOT NULL,
	"total_cached_tokens" integer DEFAULT 0 NOT NULL,
	"total_duration" integer DEFAULT 0 NOT NULL,
	"total_time_to_first_token" integer DEFAULT 0 NOT NULL,
	"total_time_to_first_reasoning_token" integer DEFAULT 0 NOT NULL,
	"time_to_first_token_count" integer DEFAULT 0 NOT NULL,
	"time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL,
	"total_cost" real DEFAULT 0 NOT NULL,
	"total_input_cost" real DEFAULT 0 NOT NULL,
	"total_output_cost" real DEFAULT 0 NOT NULL,
	"total_cached_input_cost" real DEFAULT 0 NOT NULL,
	"service_tier_explicit_count" integer DEFAULT 0 NOT NULL,
	"service_tier_implicit_count" integer DEFAULT 0 NOT NULL,
	"service_tier_served_count" integer DEFAULT 0 NOT NULL,
	"service_tier_unconfirmed_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "mpm_usage_history_mapping_minute_mode_unique" UNIQUE("model_provider_mapping_id","minute_timestamp","used_mode")
);
--> statement-breakpoint
CREATE TABLE "model_provider_mapping_usage_history_hourly" (
	"id" text PRIMARY KEY,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"model_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"model_provider_mapping_id" text NOT NULL,
	"used_mode" text NOT NULL,
	"hour_timestamp" timestamp NOT NULL,
	"logs_count" integer DEFAULT 0 NOT NULL,
	"errors_count" integer DEFAULT 0 NOT NULL,
	"client_errors_count" integer DEFAULT 0 NOT NULL,
	"gateway_errors_count" integer DEFAULT 0 NOT NULL,
	"upstream_errors_count" integer DEFAULT 0 NOT NULL,
	"completed_count" integer DEFAULT 0 NOT NULL,
	"length_limit_count" integer DEFAULT 0 NOT NULL,
	"content_filter_count" integer DEFAULT 0 NOT NULL,
	"tool_calls_count" integer DEFAULT 0 NOT NULL,
	"canceled_count" integer DEFAULT 0 NOT NULL,
	"unknown_finish_count" integer DEFAULT 0 NOT NULL,
	"cached_count" integer DEFAULT 0 NOT NULL,
	"total_input_tokens" bigint DEFAULT 0 NOT NULL,
	"total_output_tokens" bigint DEFAULT 0 NOT NULL,
	"total_tokens" bigint DEFAULT 0 NOT NULL,
	"total_reasoning_tokens" bigint DEFAULT 0 NOT NULL,
	"total_cached_tokens" bigint DEFAULT 0 NOT NULL,
	"total_duration" integer DEFAULT 0 NOT NULL,
	"total_time_to_first_token" integer DEFAULT 0 NOT NULL,
	"total_time_to_first_reasoning_token" integer DEFAULT 0 NOT NULL,
	"time_to_first_token_count" integer DEFAULT 0 NOT NULL,
	"time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL,
	"total_cost" real DEFAULT 0 NOT NULL,
	"total_input_cost" real DEFAULT 0 NOT NULL,
	"total_output_cost" real DEFAULT 0 NOT NULL,
	"total_cached_input_cost" real DEFAULT 0 NOT NULL,
	"service_tier_explicit_count" integer DEFAULT 0 NOT NULL,
	"service_tier_implicit_count" integer DEFAULT 0 NOT NULL,
	"service_tier_served_count" integer DEFAULT 0 NOT NULL,
	"service_tier_unconfirmed_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "mpm_usage_history_mapping_hour_mode_unique" UNIQUE("model_provider_mapping_id","hour_timestamp","used_mode")
);
--> statement-breakpoint
CREATE TABLE "model_usage_history" (
	"id" text PRIMARY KEY,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"model_id" text NOT NULL,
	"used_mode" text NOT NULL,
	"minute_timestamp" timestamp NOT NULL,
	"logs_count" integer DEFAULT 0 NOT NULL,
	"errors_count" integer DEFAULT 0 NOT NULL,
	"client_errors_count" integer DEFAULT 0 NOT NULL,
	"gateway_errors_count" integer DEFAULT 0 NOT NULL,
	"upstream_errors_count" integer DEFAULT 0 NOT NULL,
	"completed_count" integer DEFAULT 0 NOT NULL,
	"length_limit_count" integer DEFAULT 0 NOT NULL,
	"content_filter_count" integer DEFAULT 0 NOT NULL,
	"tool_calls_count" integer DEFAULT 0 NOT NULL,
	"canceled_count" integer DEFAULT 0 NOT NULL,
	"unknown_finish_count" integer DEFAULT 0 NOT NULL,
	"cached_count" integer DEFAULT 0 NOT NULL,
	"total_input_tokens" integer DEFAULT 0 NOT NULL,
	"total_output_tokens" integer DEFAULT 0 NOT NULL,
	"total_tokens" integer DEFAULT 0 NOT NULL,
	"total_reasoning_tokens" integer DEFAULT 0 NOT NULL,
	"total_cached_tokens" integer DEFAULT 0 NOT NULL,
	"total_duration" integer DEFAULT 0 NOT NULL,
	"total_time_to_first_token" integer DEFAULT 0 NOT NULL,
	"total_time_to_first_reasoning_token" integer DEFAULT 0 NOT NULL,
	"time_to_first_token_count" integer DEFAULT 0 NOT NULL,
	"time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL,
	"total_cost" real DEFAULT 0 NOT NULL,
	"total_input_cost" real DEFAULT 0 NOT NULL,
	"total_output_cost" real DEFAULT 0 NOT NULL,
	"total_cached_input_cost" real DEFAULT 0 NOT NULL,
	"service_tier_explicit_count" integer DEFAULT 0 NOT NULL,
	"service_tier_implicit_count" integer DEFAULT 0 NOT NULL,
	"service_tier_served_count" integer DEFAULT 0 NOT NULL,
	"service_tier_unconfirmed_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "model_usage_history_model_minute_mode_unique" UNIQUE("model_id","minute_timestamp","used_mode")
);
--> statement-breakpoint
CREATE TABLE "model_usage_history_hourly" (
	"id" text PRIMARY KEY,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"model_id" text NOT NULL,
	"used_mode" text NOT NULL,
	"hour_timestamp" timestamp NOT NULL,
	"logs_count" integer DEFAULT 0 NOT NULL,
	"errors_count" integer DEFAULT 0 NOT NULL,
	"client_errors_count" integer DEFAULT 0 NOT NULL,
	"gateway_errors_count" integer DEFAULT 0 NOT NULL,
	"upstream_errors_count" integer DEFAULT 0 NOT NULL,
	"completed_count" integer DEFAULT 0 NOT NULL,
	"length_limit_count" integer DEFAULT 0 NOT NULL,
	"content_filter_count" integer DEFAULT 0 NOT NULL,
	"tool_calls_count" integer DEFAULT 0 NOT NULL,
	"canceled_count" integer DEFAULT 0 NOT NULL,
	"unknown_finish_count" integer DEFAULT 0 NOT NULL,
	"cached_count" integer DEFAULT 0 NOT NULL,
	"total_input_tokens" bigint DEFAULT 0 NOT NULL,
	"total_output_tokens" bigint DEFAULT 0 NOT NULL,
	"total_tokens" bigint DEFAULT 0 NOT NULL,
	"total_reasoning_tokens" bigint DEFAULT 0 NOT NULL,
	"total_cached_tokens" bigint DEFAULT 0 NOT NULL,
	"total_duration" integer DEFAULT 0 NOT NULL,
	"total_time_to_first_token" integer DEFAULT 0 NOT NULL,
	"total_time_to_first_reasoning_token" integer DEFAULT 0 NOT NULL,
	"time_to_first_token_count" integer DEFAULT 0 NOT NULL,
	"time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL,
	"total_cost" real DEFAULT 0 NOT NULL,
	"total_input_cost" real DEFAULT 0 NOT NULL,
	"total_output_cost" real DEFAULT 0 NOT NULL,
	"total_cached_input_cost" real DEFAULT 0 NOT NULL,
	"service_tier_explicit_count" integer DEFAULT 0 NOT NULL,
	"service_tier_implicit_count" integer DEFAULT 0 NOT NULL,
	"service_tier_served_count" integer DEFAULT 0 NOT NULL,
	"service_tier_unconfirmed_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "model_usage_history_model_hour_mode_unique" UNIQUE("model_id","hour_timestamp","used_mode")
);
--> statement-breakpoint
CREATE INDEX "mpm_usage_history_mode_ts_model_idx" ON "model_provider_mapping_usage_history" ("used_mode","minute_timestamp","model_id");--> statement-breakpoint
CREATE INDEX "mpm_usage_history_mapping_mode_ts_idx" ON "model_provider_mapping_usage_history" ("model_provider_mapping_id","used_mode","minute_timestamp");--> statement-breakpoint
CREATE INDEX "mpm_usage_history_provider_stats_idx" ON "model_provider_mapping_usage_history" ("used_mode","minute_timestamp","provider_id","logs_count","errors_count","client_errors_count","cached_count","total_time_to_first_token","time_to_first_token_count","total_output_tokens","total_duration");--> statement-breakpoint
CREATE INDEX "mpm_usage_history_hourly_mode_ts_model_idx" ON "model_provider_mapping_usage_history_hourly" ("used_mode","hour_timestamp","model_id");--> statement-breakpoint
CREATE INDEX "mpm_usage_history_hourly_mapping_mode_ts_idx" ON "model_provider_mapping_usage_history_hourly" ("model_provider_mapping_id","used_mode","hour_timestamp");--> statement-breakpoint
CREATE INDEX "mpm_usage_history_hourly_provider_stats_idx" ON "model_provider_mapping_usage_history_hourly" ("used_mode","hour_timestamp","provider_id","logs_count","errors_count","client_errors_count","cached_count","total_time_to_first_token","time_to_first_token_count","total_output_tokens","total_duration");--> statement-breakpoint
CREATE INDEX "model_usage_history_mode_ts_model_idx" ON "model_usage_history" ("used_mode","minute_timestamp","model_id");--> statement-breakpoint
CREATE INDEX "model_usage_history_model_mode_ts_idx" ON "model_usage_history" ("model_id","used_mode","minute_timestamp");--> statement-breakpoint
CREATE INDEX "model_usage_history_hourly_mode_ts_model_idx" ON "model_usage_history_hourly" ("used_mode","hour_timestamp","model_id");--> statement-breakpoint
CREATE INDEX "model_usage_history_hourly_model_mode_ts_idx" ON "model_usage_history_hourly" ("model_id","used_mode","hour_timestamp");