ALTER TABLE "model_provider_mapping" ADD COLUMN "quantization" text;--> statement-breakpoint
ALTER TABLE "provider_draft_model" ADD COLUMN "quantization" text;
--> statement-breakpoint
UPDATE "provider_draft_model" AS draft
SET "quantization" = catalogue.quantization
FROM (VALUES
	('gpt-oss-120b', 'nebius', 'fp4'),
	('gpt-oss-120b', 'runware', 'bf16'),
	('gpt-oss-120b', 'scx-ai', 'fp8'),
	('gemma-3-27b', 'nebius', 'fp8'),
	('gemma-4-31b-it', 'deepinfra', 'fp8'),
	('gemma-4-31b-it', 'runware', 'bf16'),
	('gemma-4-31b-it', 'novita', 'bf16'),
	('gemma-4-31b-it', 'scx-ai', 'bf16'),
	('gemma-4-26b-a4b-it', 'deepinfra', 'fp8'),
	('gemma-4-26b-a4b-it', 'novita', 'bf16'),
	('mimo-v2.5-pro', 'deepinfra', 'fp8'),
	('mimo-v2.5', 'novita', 'fp8'),
	('mimo-v2.5', 'deepinfra', 'bf16'),
	('llama-3.1-8b-instruct', 'novita', 'fp8'),
	('llama-3.1-nemotron-ultra-253b', 'nebius', 'fp8'),
	('llama-3.3-70b-instruct', 'nebius', 'fp8'),
	('llama-3.3-70b-instruct', 'novita', 'bf16'),
	('llama-4-scout-17b-instruct', 'novita', 'bf16'),
	('llama-4-maverick-17b-instruct', 'novita', 'fp8'),
	('llama-4-maverick-17b-instruct', 'scx-ai', 'fp8'),
	('llama-3.2-3b-instruct', 'novita', 'bf16'),
	('deepseek-v3.2', 'novita', 'fp8'),
	('deepseek-v3.2', 'deepinfra', 'fp4'),
	('deepseek-v4-pro', 'runware', 'fp8'),
	('deepseek-v4-pro', 'deepinfra', 'fp8'),
	('deepseek-v4-pro', 'nebius', 'fp8'),
	('deepseek-v4-pro', 'canopywave', 'fp8'),
	('deepseek-v4-flash', 'runware', 'fp8'),
	('deepseek-v4-flash', 'novita', 'fp8'),
	('deepseek-v4-flash', 'deepinfra', 'fp8'),
	('deepseek-v4-flash', 'ranoai', 'fp4'),
	('deepseek-v4-flash', 'canopywave', 'fp8'),
	('deepseek-v4-flash', 'consensusprotocol', 'int8'),
	('minimax-m3', 'together-ai', 'fp4'),
	('minimax-m3', 'nebius', 'fp8'),
	('minimax-m2.7', 'novita', 'fp8'),
	('minimax-m2.5', 'novita', 'fp8'),
	('minimax-m2.5', 'nebius', 'fp4'),
	('minimax-m2.1', 'novita', 'fp8'),
	('kimi-k2', 'novita', 'fp8'),
	('kimi-k2.5', 'deepinfra', 'fp4'),
	('kimi-k2.6', 'runware', 'fp4'),
	('kimi-k2.6', 'nebius', 'int4'),
	('kimi-k2.7-code', 'nebius', 'fp4'),
	('kimi-k2.7-code', 'scx-ai-gp', 'fp8'),
	('kimi-k3', 'together-ai', 'fp4'),
	('kimi-k3', 'nebius', 'fp4'),
	('kimi-k3', 'scx-ai-gp', 'fp8'),
	('qwen3-235b-a22b-instruct-2507', 'nebius', 'fp8'),
	('qwen3-235b-a22b-instruct-2507', 'novita', 'fp8'),
	('qwen3-235b-a22b-thinking-2507', 'novita', 'fp8'),
	('qwen3-235b-a22b-fp8', 'novita', 'fp8'),
	('qwen3.5-9b', 'deepinfra', 'bf16'),
	('qwen3-32b', 'nebius', 'fp8'),
	('qwen3-32b', 'scx-ai', 'bf16'),
	('qwen2-5-vl-72b-instruct', 'nebius', 'fp8'),
	('qwen3-coder-480b-a35b-instruct', 'novita', 'fp8'),
	('qwen3-coder-30b-a3b-instruct', 'novita', 'fp8'),
	('qwen3-30b-a3b-instruct-2507', 'nebius', 'fp8'),
	('qwen3-next-80b-a3b-thinking', 'nebius', 'fp8'),
	('qwen3-next-80b-a3b-instruct', 'novita', 'bf16'),
	('qwen3-max', 'novita', 'fp8'),
	('qwen3-vl-30b-a3b-instruct', 'novita', 'bf16'),
	('qwen3-vl-30b-a3b-instruct', 'deepinfra', 'fp8'),
	('qwen3-32b-fp8', 'novita', 'fp8'),
	('qwen3-30b-a3b-fp8', 'novita', 'fp8'),
	('qwen3-4b-fp8', 'novita', 'fp8'),
	('qwen35-397b-a17b', 'nebius', 'fp4'),
	('qwen3-vl-235b-a22b-instruct', 'deepinfra', 'fp8'),
	('bge-m3', 'deepinfra', 'fp32'),
	('hermes-4-405b', 'nebius', 'fp8'),
	('hermes-4-70b', 'nebius', 'fp8'),
	('hermes-2-pro-llama-3-8b', 'novita', 'fp16'),
	('hy3', 'deepinfra', 'fp8'),
	('nemotron-3-ultra-550b', 'deepinfra', 'fp4'),
	('nemotron-3-ultra-550b', 'nebius', 'fp4'),
	('nemotron-3-super-120b', 'nebius', 'fp4'),
	('nemotron-3-nano-30b', 'nebius', 'fp8'),
	('nemotron-3-nano-omni', 'nebius', 'fp8'),
	('cosmos3-super-reasoner', 'nebius', 'fp16'),
	('minicpm-v-4.5', 'nebius', 'fp16'),
	('glm-5.3-flash', 'zai', 'fp8'),
	('glm-5.3-flash', 'novita', 'fp8'),
	('glm-5.3-flash', 'scx-ai-gp', 'fp8'),
	('glm-5.2', 'canopywave', 'fp8'),
	('glm-5.2', 'runware', 'fp4'),
	('glm-5.2', 'nebius', 'fp4'),
	('glm-5.2', 'scx-ai-gp', 'fp8'),
	('glm-5.1', 'novita', 'fp8'),
	('glm-5.1', 'deepinfra', 'fp4'),
	('glm-5.1', 'nebius', 'fp8'),
	('glm-5', 'novita', 'fp8'),
	('glm-4.5v', 'novita', 'fp8'),
	('glm-4.7', 'novita', 'fp8'),
	('glm-4.6', 'novita', 'bf16'),
	('glm-4.6v', 'novita', 'bf16')
) AS catalogue(model_id, provider_id, quantization)
WHERE draft.model_name = catalogue.model_id
  AND draft.provider_id = catalogue.provider_id;
--> statement-breakpoint
UPDATE "model_provider_mapping" AS mapping
SET "quantization" = draft.quantization
FROM "provider_draft_model" AS draft
WHERE mapping.source = 'airside'
  AND mapping.model_id = draft.model_name
  AND mapping.provider_id = draft.provider_id
  AND draft.status = 'active';
