ALTER TABLE "api_key_hourly_model_stats" ADD COLUMN "total_duration" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_model_stats" ADD COLUMN "duration_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_model_stats" ADD COLUMN "total_time_to_first_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_model_stats" ADD COLUMN "time_to_first_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_model_stats" ADD COLUMN "total_time_to_first_reasoning_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_model_stats" ADD COLUMN "time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_source_stats" ADD COLUMN "total_duration" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_source_stats" ADD COLUMN "duration_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_source_stats" ADD COLUMN "total_time_to_first_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_source_stats" ADD COLUMN "time_to_first_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_source_stats" ADD COLUMN "total_time_to_first_reasoning_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_source_stats" ADD COLUMN "time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_stats" ADD COLUMN "total_duration" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_stats" ADD COLUMN "duration_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_stats" ADD COLUMN "total_time_to_first_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_stats" ADD COLUMN "time_to_first_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_stats" ADD COLUMN "total_time_to_first_reasoning_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key_hourly_stats" ADD COLUMN "time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_model_stats" ADD COLUMN "total_duration" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_model_stats" ADD COLUMN "duration_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_model_stats" ADD COLUMN "total_time_to_first_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_model_stats" ADD COLUMN "time_to_first_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_model_stats" ADD COLUMN "total_time_to_first_reasoning_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_model_stats" ADD COLUMN "time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_source_stats" ADD COLUMN "total_duration" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_source_stats" ADD COLUMN "duration_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_source_stats" ADD COLUMN "total_time_to_first_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_source_stats" ADD COLUMN "time_to_first_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_source_stats" ADD COLUMN "total_time_to_first_reasoning_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_source_stats" ADD COLUMN "time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_stats" ADD COLUMN "total_duration" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_stats" ADD COLUMN "duration_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_stats" ADD COLUMN "total_time_to_first_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_stats" ADD COLUMN "time_to_first_token_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_stats" ADD COLUMN "total_time_to_first_reasoning_token" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_hourly_stats" ADD COLUMN "time_to_first_reasoning_token_count" integer DEFAULT 0 NOT NULL;