import { readFile, mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import tailwind from "@tailwindcss/postcss";
import { build } from "esbuild";
import postcss from "postcss";

const root = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"../..",
);
const resolve = createRequire(path.join(root, "package.json")).resolve;
const shadcn = path.dirname(resolve("@json-render/shadcn"));
const cssPath = path.join(root, "src/app/globals.css");
async function main() {
	const css = await postcss([tailwind({ base: root })]).process(
		`${await readFile(cssPath, "utf8")}\n@source "${shadcn}/*.{js,mjs}";\nbody { margin: 0; background: var(--background); color: var(--foreground); font-family: -apple-system, sans-serif; } #preview { padding: 20px; min-height: 100vh; overflow-wrap: anywhere; } #preview .grid { width: 100%; min-width: 0; } #preview .grid > * { min-width: 0; } #preview img { max-width: 100%; } @media (max-width: 600px) { #preview .grid { grid-template-columns: minmax(0, 1fr); } }`,
		{ from: cssPath },
	);
	const bundle = await build({
		absWorkingDir: root,
		entryPoints: ["src/components/playground/native-canvas-preview.tsx"],
		tsconfig: "tsconfig.json",
		bundle: true,
		write: false,
		minify: true,
		format: "iife",
		platform: "browser",
		target: "safari16",
		jsx: "automatic",
		define: { "process.env.NODE_ENV": '"production"' },
	});
	const script = bundle.outputFiles[0].text.replaceAll(
		"</script",
		"<\\/script",
	);
	const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src https: data: blob:; font-src data:; connect-src https: data: blob:; base-uri 'none'; form-action 'none'"><style>${css.css.replaceAll("</style", "<\\/style")}</style></head><body><main id="preview"></main><script>${script}</script></body></html>`;
	const output = path.resolve(root, "../mobile/src/generated");
	await mkdir(output, { recursive: true });
	await writeFile(
		path.join(output, "canvas-preview.ts"),
		`// Generated by playground build:native-canvas.\nexport const canvasPreviewHTML = ${JSON.stringify(html)};\n`,
	);
	console.info(
		`Bundled Canvas preview (${Math.round(html.length / 1024)} KiB).`,
	);
}
void main().catch((error: unknown) => {
	console.error(error);
	process.exitCode = 1;
});
