CREATE TABLE "global_provider_key_model_stats" (
	"id" text PRIMARY KEY,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"day_timestamp" timestamp NOT NULL,
	"provider_key_id" text NOT NULL,
	"used_model" text NOT NULL,
	"used_provider" text NOT NULL,
	"used_mode" text DEFAULT 'unknown' NOT NULL,
	"org_kind" text DEFAULT 'unknown' NOT NULL,
	"request_count" integer DEFAULT 0 NOT NULL,
	"error_count" integer DEFAULT 0 NOT NULL,
	"cache_count" integer DEFAULT 0 NOT NULL,
	"streamed_count" integer DEFAULT 0 NOT NULL,
	"non_streamed_count" integer DEFAULT 0 NOT NULL,
	"completed_count" integer DEFAULT 0 NOT NULL,
	"length_limit_count" integer DEFAULT 0 NOT NULL,
	"content_filter_count" integer DEFAULT 0 NOT NULL,
	"tool_calls_count" integer DEFAULT 0 NOT NULL,
	"canceled_count" integer DEFAULT 0 NOT NULL,
	"unknown_finish_count" integer DEFAULT 0 NOT NULL,
	"client_error_count" integer DEFAULT 0 NOT NULL,
	"gateway_error_count" integer DEFAULT 0 NOT NULL,
	"upstream_error_count" integer DEFAULT 0 NOT NULL,
	"input_tokens" numeric DEFAULT '0' NOT NULL,
	"output_tokens" numeric DEFAULT '0' NOT NULL,
	"total_tokens" numeric DEFAULT '0' NOT NULL,
	"reasoning_tokens" numeric DEFAULT '0' NOT NULL,
	"cached_tokens" numeric DEFAULT '0' NOT NULL,
	"cache_write_tokens" numeric DEFAULT '0' NOT NULL,
	"cost" real DEFAULT 0 NOT NULL,
	"input_cost" real DEFAULT 0 NOT NULL,
	"output_cost" real DEFAULT 0 NOT NULL,
	"request_cost" real DEFAULT 0 NOT NULL,
	"data_storage_cost" real DEFAULT 0 NOT NULL,
	"discount_savings" real DEFAULT 0 NOT NULL,
	"image_input_cost" real DEFAULT 0 NOT NULL,
	"image_output_cost" real DEFAULT 0 NOT NULL,
	"audio_input_cost" real DEFAULT 0 NOT NULL,
	"audio_output_cost" real DEFAULT 0 NOT NULL,
	"video_output_cost" real DEFAULT 0 NOT NULL,
	"cached_input_cost" real DEFAULT 0 NOT NULL,
	"cache_write_input_cost" real DEFAULT 0 NOT NULL,
	CONSTRAINT "global_provider_key_model_stats_day_key_model_unique" UNIQUE("day_timestamp","provider_key_id","used_model","used_provider","used_mode","org_kind")
);
--> statement-breakpoint
CREATE INDEX "global_provider_key_model_stats_day_timestamp_idx" ON "global_provider_key_model_stats" ("day_timestamp");--> statement-breakpoint
CREATE INDEX "global_provider_key_model_stats_key_day_idx" ON "global_provider_key_model_stats" ("provider_key_id","day_timestamp");