import type { ModelDefinition } from "@/models.js";

export const alibabaModels = [
	{
		id: "qwen-max",
		name: "Qwen Max",
		description: "Alibaba's flagship Qwen model with vision and tool support.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-max",
				inputPrice: 1.6 / 1e6,
				outputPrice: 6.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-max-latest",
		name: "Qwen Max Latest",
		description: "Latest Qwen Max with enhanced capabilities.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-max-latest",
				inputPrice: 1.6 / 1e6,
				outputPrice: 6.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-plus",
		name: "Qwen Plus",
		description: "Mid-tier Qwen model balancing speed and capability.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-plus",
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-plus-latest",
		name: "Qwen Plus Latest",
		description: "Updated Qwen Plus with extended context support.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-plus-latest",
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 32000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-flash",
		name: "Qwen Flash",
		description: "Fast, cost-effective Qwen for high-volume tasks.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-flash",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 32000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-omni-turbo",
		name: "Qwen Omni Turbo",
		description: "Multimodal Qwen with vision support.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-omni-turbo",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.8 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-turbo",
		name: "Qwen Turbo",
		description: "Fastest Qwen model for quick responses.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-turbo",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-coder-plus",
		name: "Qwen3 Coder Plus",
		description: "Advanced Qwen for code generation.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen3-coder-plus",
				inputPrice: 6 / 1e6,
				outputPrice: 60 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 66000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-qwq-32b",
		name: "Qwen QwQ 32B",
		description: "Qwen 32B reasoning model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/QwQ-32B",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.45 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "qwen3-235b-a22b-instruct-2507",
		name: "Qwen3 235B A22B Instruct 2507",
		description: "Large Qwen 3 MoE instruction model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-235B-A22B-Instruct-2507",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				reasoning: false,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-235b-a22b-thinking-2507",
		name: "Qwen3 235B A22B Thinking 2507",
		description: "Qwen 3 MoE with reasoning capabilities.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-235B-A22B-Thinking-2507",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				stability: "unstable",
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-14b",
		name: "Qwen3 14B",
		description: "Mid-size Qwen 3 model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-14B",
				inputPrice: 0.08 / 1e6,
				outputPrice: 0.24 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "qwen3-32b",
		name: "Qwen3 32B",
		description: "Mid-size Qwen 3 model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-32B",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-30b-a3b",
		name: "Qwen3 30B A3B",
		description: "Mid-size Qwen 3 MoE model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-30B-A3B",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "qwen25-coder-7b",
		name: "Qwen2.5 Coder 7B",
		description: "Qwen 2.5 code model, 7B size.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-Coder-7B-fast",
				inputPrice: 0.01 / 1e6,
				outputPrice: 0.03 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen25-32b-instruct",
		name: "Qwen2.5 32B Instruct",
		description: "Qwen 2.5 instruction model, 32B size.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-32B-Instruct",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-09-10"),
			},
		],
	},
	{
		id: "qwen25-72b-instruct",
		name: "Qwen2.5 72B Instruct",
		description: "Qwen 2.5 instruction model, 72B size.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-72B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "qwen2-vl-72b-instruct",
		name: "Qwen2 VL 72B Instruct",
		description: "Vision-language Qwen 2 model, 72B size.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2-VL-72B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
				deactivatedAt: new Date("2025-09-10"),
			},
		],
	},
	{
		id: "qwen2-5-vl-72b-instruct",
		name: "Qwen2.5 VL 72B Instruct",
		description: "Vision-language Qwen 2.5 model, 72B size.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-VL-72B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-coder-480b-a35b-instruct",
		name: "Qwen3 Coder 480B A35B Instruct",
		description: "Code-specialized Qwen 3 MoE, 480B size.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.8 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-coder-30b-a3b-instruct",
		name: "Qwen3 Coder 30B A3B Instruct",
		description: "Code-specialized Qwen 3 MoE, 30B size.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-30b-a3b-instruct-2507",
		name: "Qwen3 30B A3B Instruct 2507",
		description: "Qwen 3 MoE instruction model, July 2025.",
		family: "alibaba",
		releasedAt: new Date("2025-07-01"),
		publishedAt: new Date("2025-07-01"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-30B-A3B-Instruct-2507",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-30b-a3b-thinking-2507",
		name: "Qwen3 30B A3B Thinking 2507",
		description: "Qwen 3 MoE with reasoning, July 2025.",
		family: "alibaba",
		releasedAt: new Date("2025-07-01"),
		publishedAt: new Date("2025-07-01"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-30B-A3B-Thinking-2507",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-vl-max",
		name: "Qwen VL Max",
		description: "Vision-language Qwen flagship model.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-vl-max",
				inputPrice: 0.8 / 1e6,
				outputPrice: 3.2 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-vl-plus",
		name: "Qwen VL Plus",
		description: "Vision-language Qwen mid-tier model.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		publishedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-vl-plus",
				inputPrice: 0.21 / 1e6,
				outputPrice: 0.64 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-next-80b-a3b-thinking",
		name: "Qwen3 Next 80B A3B Thinking",
		description: "Preview Qwen 3 Next with reasoning.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen3-next-80b-a3b-thinking",
				inputPrice: 0.5 / 1e6,
				outputPrice: 6 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "qwen3-next-80b-a3b-instruct",
		name: "Qwen3 Next 80B A3B Instruct",
		description: "Preview Qwen 3 Next instruction model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen3-next-80b-a3b-instruct",
				inputPrice: 0.5 / 1e6,
				outputPrice: 2 / 1e6,
				requestPrice: 0,
				contextSize: 129024,
				maxOutput: 32768,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-max",
		name: "Qwen3 Max",
		description: "Top-tier Qwen 3 with reasoning and vision support.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen3-max-preview",
				inputPrice: 3 / 1e6,
				outputPrice: 15 / 1e6,
				cachedInputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: 32800,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-coder",
		name: "Qwen3 Coder",
		description: "General Qwen 3 coding model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-30"),
		publishedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "canopywave",
				modelName: "qwen/qwen3-coder",
				inputPrice: 0.22 / 1e6,
				outputPrice: 0.95 / 1e6,
				discount: 0.75,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
