import type { ModelDefinition } from "@/models.js";

export const anthropicModels = [
	{
		id: "claude-3-7-sonnet",
		name: "Claude 3.7 Sonnet",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-7-sonnet-latest",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-3-7-sonnet-20250219-v1:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-5-haiku-20241022",
		name: "Claude 3.5 Haiku (2024-10-22)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-5-haiku-20241022",
				inputPrice: 0.8 / 1e6,
				outputPrice: 4.0 / 1e6,
				cachedInputPrice: 0.08 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				providerId: "routeway-discount",
				stability: "unstable" as const,
				modelName: "claude-3-5-haiku-20241022-v1:0",
				inputPrice: 0.8 / 1e6,
				outputPrice: 4.0 / 1e6,
				cachedInputPrice: 0.08 / 1e6,
				discount: 0.5,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-7-sonnet-20250219",
		name: "Claude 3.7 Sonnet (2025-02-19)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-7-sonnet-20250219",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				reasoning: true,
				tools: true,
			},
			{
				test: "skip",
				providerId: "routeway-discount",
				stability: "unstable" as const,
				modelName: "claude-3-7-sonnet-20250219-v1:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				discount: 0.5,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				reasoning: true,
				reasoningOutput: "omit",
				tools: true,
			},
		],
	},
	{
		id: "claude-3-5-sonnet-20241022",
		name: "Claude 3.5 Sonnet (2024-10-22)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: new Date("2025-10-22T00:00:00Z"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-5-sonnet-20241022",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-3-5-sonnet-20241022-v2:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-2.1",
		name: "Claude 2.1",
		family: "anthropic",
		deprecatedAt: new Date("2025-06-15T00:00:00Z"),
		deactivatedAt: new Date("2025-07-21T16:00:00Z"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-2.1",
				inputPrice: 8.0 / 1e6,
				outputPrice: 24.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
	},
	{
		id: "claude-sonnet-4-20250514",
		name: "Claude Sonnet 4 (2025-05-14)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-sonnet-4-20250514",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				test: "skip",
				providerId: "routeway-discount",
				stability: "unstable" as const,
				modelName: "claude-sonnet-4-20250514-v1:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				discount: 0.5,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-sonnet-4-20250514-v1:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-sonnet-4-5",
		name: "Claude Sonnet 4.5",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-sonnet-4-5",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				reasoning: true,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				test: "skip",
				providerId: "routeway-discount",
				stability: "unstable" as const,
				modelName: "claude-sonnet-4-5-20250929-v1:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				discount: 0.5,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-sonnet-4-5-20250929-v1:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-haiku-4-5",
		name: "Claude Haiku 4.5",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-haiku-4-5",
				inputPrice: 1.0 / 1e6,
				outputPrice: 5.0 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-opus-4-20250514",
		name: "Claude Opus 4 (2025-05-14)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-opus-4-20250514",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				test: "skip",
				providerId: "routeway-discount",
				stability: "unstable" as const,
				modelName: "claude-opus-4-20250514-v1:0",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				discount: 0.5,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-opus-4-20250514-v1:0",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-opus-4-1-20250805",
		name: "Claude Opus 4.1",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-opus-4-1-20250805",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				reasoning: true,
				tools: true,
			},
			{
				test: "skip",
				providerId: "routeway-discount",
				stability: "unstable" as const,
				modelName: "claude-opus-4-1-20250805-v1:0",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				discount: 0.5,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				reasoning: true,
				reasoningOutput: "omit",
				tools: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-opus-4-1-20250805-v1:0",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				reasoning: true,
				reasoningOutput: "omit",
				tools: true,
			},
		],
	},
	{
		id: "claude-3-5-sonnet-20240620",
		name: "Claude 3.5 Sonnet (Old)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-5-sonnet-20240620",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-5-sonnet",
		name: "Claude 3.5 Sonnet",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-5-sonnet-latest",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-5-haiku",
		name: "Claude 3.5 Haiku",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-5-haiku-latest",
				inputPrice: 0.8 / 1e6,
				outputPrice: 4.0 / 1e6,
				cachedInputPrice: 0.08 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-3-5-haiku-20241022-v1:0",
				inputPrice: 0.8 / 1e6,
				outputPrice: 4.0 / 1e6,
				cachedInputPrice: 0.08 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-opus",
		name: "Claude 3 Opus",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-opus-20240229",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-haiku",
		name: "Claude 3 Haiku",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-haiku-20240307",
				inputPrice: 0.25 / 1e6,
				outputPrice: 1.25 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
