import type { ModelDefinition } from "@/models.js";

export const deepseekModels = [
	{
		id: "deepseek-v3",
		name: "DeepSeek V3",
		description:
			"Large-scale Chinese AI model with strong multilingual capabilities.",
		family: "deepseek",
		releasedAt: new Date("2024-12-26"),
		publishedAt: new Date("2024-12-26"),
		providers: [
			{
				providerId: "cloudrift",
				modelName: "deepseek-ai/DeepSeek-V3",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 163840,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "nebius",
				stability: "unstable" as const,
				modelName: "deepseek-ai/DeepSeek-V3",
				inputPrice: 0.5 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "deepseek-r1-0528",
		name: "DeepSeek R1 (0528)",
		description: "May 2028 version of DeepSeek R1 reasoning model.",
		family: "deepseek",
		releasedAt: new Date("2025-05-28"),
		publishedAt: new Date("2025-05-28"),
		providers: [
			{
				providerId: "cloudrift",
				modelName: "deepseek-ai/DeepSeek-R1-0528",
				inputPrice: 0.25 / 1e6,
				outputPrice: 1 / 1e6,
				requestPrice: 0,
				contextSize: 32770,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				stability: "unstable" as const,
				jsonOutput: false,
			},
			{
				providerId: "nebius",
				modelName: "deepseek-ai/DeepSeek-R1-0528",
				inputPrice: 0.8 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				stability: "unstable" as const,
				jsonOutput: false,
			},
		],
	},
	{
		id: "deepseek-r1-distill-llama-70b",
		name: "DeepSeek R1 Distill Llama 70B",
		description: "DeepSeek R1 distilled into Llama 70B architecture.",
		family: "deepseek",
		stability: "beta" as const,
		releasedAt: new Date("2025-01-20"),
		publishedAt: new Date("2025-01-20"),
		providers: [
			{
				providerId: "groq",
				modelName: "deepseek-r1-distill-llama-70b",
				inputPrice: 0.75 / 1e6,
				outputPrice: 0.99 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-10-09"),
			},
		],
	},
	{
		id: "deepseek-v3.1",
		name: "DeepSeek V3.1",
		description:
			"Updated DeepSeek V3 with vision, tools, and improved performance.",
		family: "deepseek",
		releasedAt: new Date("2025-08-21"),
		publishedAt: new Date("2025-08-21"),
		providers: [
			{
				providerId: "canopywave",
				modelName: "deepseek/deepseek-chat-v3.1",
				deactivatedAt: new Date("2025-12-15"),
				inputPrice: 0.27 / 1e6,
				outputPrice: 1.0 / 1e6,
				discount: 0.9,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				providerId: "bytedance",
				modelName: "deepseek-v3-1-250821",
				inputPrice: 0.56 / 1e6,
				cachedInputPrice: 0.112 / 1e6,
				outputPrice: 1.68 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 32768,
				reasoning: true,
				reasoningOutput: "omit" as const,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "deepseek-v3.2",
		name: "DeepSeek V3.2",
		description:
			"Latest DeepSeek V3 with vision, tools, and improved performance.",
		family: "deepseek",
		releasedAt: new Date("2025-12-02"),
		publishedAt: new Date("2025-12-02"),
		providers: [
			{
				providerId: "deepseek",
				modelName: "deepseek-chat",
				inputPrice: 0.28 / 1e6,
				outputPrice: 0.42 / 1e6,
				cachedInputPrice: 0.028 / 1e6,
				requestPrice: 0,
				contextSize: 163840,
				maxOutput: undefined,
				jsonOutput: true,
				streaming: true,
				vision: true,
				tools: true,
			},
			{
				providerId: "canopywave",
				modelName: "deepseek/deepseek-chat-v3.2",
				test: "skip",
				inputPrice: 0.28 / 1e6,
				outputPrice: 0.42 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				providerId: "bytedance",
				modelName: "deepseek-v3-2-251201",
				inputPrice: 0.28 / 1e6,
				cachedInputPrice: 0.056 / 1e6,
				outputPrice: 0.42 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				reasoning: true,
				reasoningOutput: "omit" as const,
				maxOutput: 131072,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
] as const satisfies ModelDefinition[];
