import type { ModelDefinition } from "@/models.js";

export const embercloudModels = [
	{
		id: "glm-5",
		name: "GLM-5",
		family: "zhipu",
		description:
			"Zhipu's most capable GLM-5 model with reasoning and tool support.",
		providers: [
			{
				providerId: "embercloud",
				modelName: "glm-5",
				inputPrice: 0.72 / 1e6,
				outputPrice: 2.3 / 1e6,
				cachedInputPrice: 0.144 / 1e6,
				requestPrice: 0,
				contextSize: 203000,
				maxOutput: 131000,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: false,
				supportedParameters: [
					"messages",
					"model",
					"stream",
					"stream_options",
					"temperature",
					"top_p",
					"max_tokens",
					"max_completion_tokens",
					"seed",
					"stop",
					"response_format",
					"tools",
					"tool_choice",
					"parallel_tool_calls",
					"reasoning",
				],
			},
		],
	},
	{
		id: "glm-4.7",
		name: "GLM-4.7",
		family: "zhipu",
		description:
			"Zhipu's GLM-4.7 model with reasoning, tool support, and 200K context.",
		providers: [
			{
				providerId: "embercloud",
				modelName: "glm-4.7",
				inputPrice: 0.38 / 1e6,
				outputPrice: 1.98 / 1e6,
				cachedInputPrice: 0.19 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 131000,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
				supportedParameters: [
					"messages",
					"model",
					"stream",
					"stream_options",
					"temperature",
					"top_p",
					"max_tokens",
					"max_completion_tokens",
					"seed",
					"stop",
					"response_format",
					"logprobs",
					"top_logprobs",
					"tools",
					"tool_choice",
					"parallel_tool_calls",
					"reasoning",
				],
			},
		],
	},
	{
		id: "glm-4.7-flash",
		name: "GLM-4.7 Flash",
		family: "zhipu",
		description:
			"Fast and affordable GLM-4.7 Flash model with 200K context window.",
		providers: [
			{
				providerId: "embercloud",
				modelName: "glm-4.7-flash",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.01 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 131000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"messages",
					"model",
					"stream",
					"stream_options",
					"temperature",
					"top_p",
					"max_tokens",
					"max_completion_tokens",
					"seed",
					"stop",
					"response_format",
					"logprobs",
					"top_logprobs",
					"tools",
					"tool_choice",
					"parallel_tool_calls",
				],
			},
		],
	},
	{
		id: "glm-4.5",
		name: "GLM-4.5",
		family: "zhipu",
		description: "Zhipu's GLM-4.5 model with 131K context and tool support.",
		providers: [
			{
				providerId: "embercloud",
				modelName: "glm-4.5",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.2 / 1e6,
				cachedInputPrice: 0.11 / 1e6,
				requestPrice: 0,
				contextSize: 131000,
				maxOutput: 96000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"messages",
					"model",
					"stream",
					"stream_options",
					"temperature",
					"top_p",
					"max_tokens",
					"max_completion_tokens",
					"seed",
					"stop",
					"response_format",
					"logprobs",
					"top_logprobs",
					"tools",
					"tool_choice",
					"parallel_tool_calls",
				],
			},
		],
	},
	{
		id: "glm-4.5-air",
		name: "GLM-4.5 Air",
		family: "zhipu",
		description:
			"Affordable GLM-4.5 Air model with 131K context and tool support.",
		providers: [
			{
				providerId: "embercloud",
				modelName: "glm-4.5-air",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.85 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 131000,
				maxOutput: 96000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"messages",
					"model",
					"stream",
					"stream_options",
					"temperature",
					"top_p",
					"max_tokens",
					"max_completion_tokens",
					"seed",
					"stop",
					"response_format",
					"logprobs",
					"top_logprobs",
					"tools",
					"tool_choice",
					"parallel_tool_calls",
				],
			},
		],
	},
	{
		id: "qwen3-coder-next",
		name: "Qwen3 Coder Next",
		family: "alibaba",
		description:
			"Alibaba's Qwen3 Coder Next model optimized for coding tasks with 262K context.",
		providers: [
			{
				providerId: "embercloud",
				modelName: "qwen3-coder-next",
				inputPrice: 0.108 / 1e6,
				outputPrice: 0.675 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"messages",
					"model",
					"stream",
					"stream_options",
					"temperature",
					"top_p",
					"max_tokens",
					"max_completion_tokens",
					"seed",
					"stop",
					"response_format",
					"tools",
					"tool_choice",
					"parallel_tool_calls",
				],
			},
		],
	},
] as const satisfies ModelDefinition[];
