import type { ModelDefinition } from "@llmgateway/models";

export const googleModels = [
	{
		id: "gemini-2.5-pro",
		name: "Gemini 2.5 Pro",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-pro",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
			},
		],
	},
	{
		id: "gemini-2.5-pro-preview-05-06",
		name: "Gemini 2.5 Pro Preview (05-06)",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-pro-preview-05-06",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
			},
		],
	},
	{
		id: "gemini-2.5-pro-preview-06-05",
		name: "Gemini 2.5 Pro Preview (06-05)",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-pro-preview-06-05",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
			},
		],
	},
	{
		id: "gemini-2.5-flash-preview-04-17",
		name: "Gemini 2.5 Flash Preview (04-17)",
		deprecatedAt: undefined,
		deactivatedAt: new Date("2025-07-22"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-flash-preview-04-17",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
			},
		],
	},
	{
		id: "gemini-2.5-flash-preview-05-20",
		name: "Gemini 2.5 Flash Preview (05-20)",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-flash-preview-05-20",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
			},
		],
	},
	{
		id: "gemini-2.5-flash",
		name: "Gemini 2.5 Flash",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-flash",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
			},
		],
	},
	{
		id: "gemini-2.5-flash-preview-04-17-thinking",
		name: "Gemini 2.5 Flash Preview Thinking (04-17)",
		deprecatedAt: undefined,
		deactivatedAt: new Date("2025-07-22"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-flash-preview-04-17-thinking",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
			},
		],
	},
	{
		id: "gemini-1.5-pro",
		name: "Gemini 1.5 Pro",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-1.5-pro",
				inputPrice: 0.0375 / 1e6,
				outputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
			},
		],
	},
	{
		id: "gemini-1.5-flash",
		name: "Gemini 1.5 Flash",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-1.5-flash",
				inputPrice: 0.0375 / 1e6,
				outputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
			},
		],
	},
	{
		id: "gemini-1.5-flash-8b",
		name: "Gemini 1.5 Flash 8B",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-1.5-flash-8b",
				inputPrice: 0.0375 / 1e6,
				outputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
			},
		],
	},
	{
		id: "gemini-2.0-flash-lite",
		name: "Gemini 2.0 Flash Lite",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.0-flash-lite",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
			},
		],
	},
	{
		id: "gemini-2.0-flash",
		name: "Gemini 2.0 Flash",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.0-flash",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: false,
				vision: false,
			},
		],
	},
	{
		id: "gemma-3n-e2b-it",
		name: "Gemma 3n E2B IT",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3n-e2b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
			},
		],
	},
	{
		id: "gemma-3n-e4b-it",
		name: "Gemma 3n E4B IT",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3n-e4b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
			},
		],
	},
	{
		id: "gemma-3-1b-it",
		name: "Gemma 3 1B IT",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3-1b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
			},
		],
	},
	{
		id: "gemma-3-4b-it",
		name: "Gemma 3 4B IT",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3-4b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
			},
		],
	},
	{
		id: "gemma-3-12b-it",
		name: "Gemma 3 12B IT",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3-12b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
			},
		],
	},
	{
		id: "gemma2-9b-it",
		name: "Gemma2 9B IT",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "groq",
				modelName: "gemma2-9b-it",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 8129,
				maxOutput: undefined,
				streaming: true,
				vision: false,
			},
		],
		jsonOutput: true,
	},
] as const satisfies ModelDefinition[];
