import type { ModelDefinition } from "@/models.js";

export const minimaxModels = [
	{
		id: "minimax-m2.7",
		name: "MiniMax M2.7",
		description:
			"MiniMax M2.7 with stronger reasoning and coding performance for complex tasks.",
		family: "minimax",
		providers: [
			{
				providerId: "minimax",
				modelName: "MiniMax-M2.7",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "novita",
				modelName: "minimax/minimax-m2.7",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "together-ai",
				modelName: "MiniMaxAI/MiniMax-M2.7",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 196608,
				maxOutput: 196608,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "minimax-m2.7-highspeed",
		name: "MiniMax M2.7 Highspeed",
		description:
			"Highspeed MiniMax M2.7 variant with the same model quality and lower latency.",
		family: "minimax",
		providers: [
			{
				providerId: "minimax",
				modelName: "MiniMax-M2.7-highspeed",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "minimax-m2.5",
		name: "MiniMax M2.5",
		description: "MiniMax M2.5 with enhanced reasoning and tool support.",
		family: "minimax",
		releasedAt: new Date("2026-02-15"),
		providers: [
			{
				providerId: "minimax",
				modelName: "MiniMax-M2.5",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "novita",
				modelName: "minimax/minimax-m2.5",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				deactivatedAt: new Date("2026-04-27"),
				providerId: "together-ai",
				modelName: "MiniMaxAI/MiniMax-M2.5",
				inputPrice: 0.3 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 228700,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "embercloud",
				modelName: "minimax-m2.5",
				inputPrice: 0.2 / 1e6,
				outputPrice: 1.2 / 1e6,
				cachedInputPrice: 0.04 / 1e6,
				requestPrice: 0,
				contextSize: 196608,
				maxOutput: 196608,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: false,
				tools: true,
				// Embercloud leaks <think> tags into JSON output, breaking json_object mode
				jsonOutput: false,
				supportedParameters: [
					"messages",
					"model",
					"stream",
					"stream_options",
					"temperature",
					"top_p",
					"max_tokens",
					"max_completion_tokens",
					"seed",
					"stop",
					"response_format",
					"tools",
					"tool_choice",
					"parallel_tool_calls",
				],
			},
			{
				providerId: "nebius",
				// Streaming tool calls and response_format: json_object are unreliable on Nebius
				stability: "unstable",
				modelName: "MiniMaxAI/MiniMax-M2.5",
				inputPrice: 0.3 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "minimax-m2.5-highspeed",
		name: "MiniMax M2.5 Highspeed",
		description:
			"Highspeed MiniMax M2.5 variant with the same model quality and lower latency.",
		family: "minimax",
		providers: [
			{
				providerId: "minimax",
				modelName: "MiniMax-M2.5-highspeed",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "minimax-m2",
		name: "MiniMax M2",
		description: "MiniMax M2 model with reasoning and tool support.",
		family: "minimax",
		releasedAt: new Date("2025-10-27"),
		providers: [
			{
				providerId: "minimax",
				modelName: "MiniMax-M2",
				inputPrice: 0.2 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				outputPrice: 1.0 / 1e6,
				requestPrice: 0,
				contextSize: 196608,
				maxOutput: 131072,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "minimax-m2.1",
		name: "MiniMax M2.1",
		description:
			"MiniMax M2.1 is a 10B-activated open-source coding and agent model with function calling, structured output, and reasoning support.",
		family: "minimax",
		releasedAt: new Date("2025-12-23"),
		providers: [
			{
				providerId: "minimax",
				modelName: "MiniMax-M2.1",
				inputPrice: 0.27 / 1e6,
				outputPrice: 1.1 / 1e6,
				requestPrice: 0,
				contextSize: 196608,
				maxOutput: 131072,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "novita",
				test: "skip",
				modelName: "minimax/minimax-m2.1",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131072,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: false,
			},
		],
	},
	{
		id: "minimax-m2.1-lightning",
		name: "MiniMax M2.1 Lightning",
		description:
			"MiniMax M2.1 Lightning is a faster variant of M2.1 with lower latency for coding tasks.",
		family: "minimax",
		releasedAt: new Date("2025-12-23"),
		providers: [
			{
				providerId: "minimax",
				modelName: "MiniMax-M2.1-lightning",
				inputPrice: 0.12 / 1e6,
				outputPrice: 0.48 / 1e6,
				requestPrice: 0,
				contextSize: 196608,
				maxOutput: 131072,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "minimax-text-01",
		name: "MiniMax Text 01",
		description:
			"MiniMax-Text-01 is a 456B parameter model with 4M token context using Lightning Attention.",
		family: "minimax",
		releasedAt: new Date("2025-01-15"),
		providers: [
			{
				providerId: "minimax",
				modelName: "MiniMax-Text-01",
				inputPrice: 0.2 / 1e6,
				outputPrice: 1.1 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 131072,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				reasoningOutput: "omit",
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
] as const satisfies ModelDefinition[];
