import type { ModelDefinition } from "@/models.js";

export const minimaxModels = [
	{
		id: "minimax-m2",
		name: "MiniMax M2",
		description: "MiniMax M2 model with reasoning and tool support.",
		family: "minimax",
		releasedAt: new Date("2025-06-01"),
		publishedAt: new Date("2025-06-01"),
		providers: [
			{
				providerId: "canopywave",
				modelName: "minimax/minimax-m2",
				deactivatedAt: new Date("2026-01-01"),
				inputPrice: 0.25 / 1e6,
				outputPrice: 1.0 / 1e6,
				discount: 0.25,
				requestPrice: 0,
				contextSize: 196608,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "minimax-m2.1",
		name: "MiniMax M2.1",
		description:
			"MiniMax M2.1 is a 10B-activated open-source coding and agent model with function calling, structured output, and reasoning support.",
		family: "minimax",
		releasedAt: new Date("2025-12-26"),
		publishedAt: new Date("2025-12-27"),
		providers: [
			{
				providerId: "novita",
				modelName: "minimax/minimax-m2.1",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131072,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: false,
			},
			{
				providerId: "canopywave",
				modelName: "minimax/minimax-m2.1",
				inputPrice: 0.27 / 1e6,
				outputPrice: 1.08 / 1e6,
				discount: 0.25,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131072,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
