import type { ModelDefinition } from "@/models.js";

export const mistralModels = [
	{
		id: "mistral-large-latest",
		name: "Mistral Large Latest",
		description: "Mistral's flagship large model for complex reasoning tasks.",
		family: "mistral",
		releasedAt: new Date("2025-12-02"),
		providers: [
			{
				providerId: "mistral",
				modelName: "mistral-large-latest",
				inputPrice: 0.000004,
				outputPrice: 0.000012,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "mixtral-8x7b-instruct-together",
		name: "Mixtral 8x7B Instruct",
		description: "Mixture-of-experts model with 8x7B architecture.",
		family: "mistral",
		releasedAt: new Date("2023-12-10"),
		providers: [
			{
				providerId: "together.ai",
				modelName: "mistralai/mixtral-8x7b-instruct-v0.1",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "mistral-7b-instruct-together",
		name: "Mistral 7B Instruct",
		description: "Compact 7B instruction-tuned Mistral model.",
		family: "mistral",
		releasedAt: new Date("2023-09-27"),
		providers: [
			{
				deactivatedAt: new Date("2025-11-13"),
				providerId: "together.ai",
				modelName: "mistralai/mistral-7b-instruct-v0.1",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "pixtral-large-latest",
		name: "Pixtral Large Latest",
		description: "Mistral's multimodal model with vision capabilities.",
		family: "mistral",
		releasedAt: new Date("2024-11-18"),
		providers: [
			{
				providerId: "mistral",
				modelName: "pixtral-large-latest",
				inputPrice: 0.000004,
				outputPrice: 0.000012,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "mistral-large-2512",
		name: "Mistral Large 3",
		description:
			"Mistral's latest flagship model with 675B parameters and MoE architecture.",
		family: "mistral",
		releasedAt: new Date("2025-12-02"),
		providers: [
			{
				providerId: "mistral",
				modelName: "mistral-large-2512",
				inputPrice: 0.5 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "mistral-small-2506",
		name: "Mistral Small 3.2",
		description: "Lightweight 24B model for fast, efficient tasks.",
		family: "mistral",
		releasedAt: new Date("2025-06-20"),
		providers: [
			{
				providerId: "mistral",
				modelName: "mistral-small-2506",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "ministral-14b-2512",
		name: "Ministral 14B",
		description:
			"Largest Ministral model optimized for edge and local deployment.",
		family: "mistral",
		releasedAt: new Date("2025-12-02"),
		providers: [
			{
				providerId: "mistral",
				modelName: "ministral-14b-2512",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "ministral-8b-2512",
		name: "Ministral 8B",
		description: "Mid-size Ministral model for edge and local deployment.",
		family: "mistral",
		releasedAt: new Date("2025-12-02"),
		providers: [
			{
				providerId: "mistral",
				modelName: "ministral-8b-2512",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "ministral-3b-2512",
		name: "Ministral 3B",
		description: "Smallest Ministral model for efficient edge deployment.",
		family: "mistral",
		releasedAt: new Date("2025-12-02"),
		providers: [
			{
				providerId: "mistral",
				modelName: "ministral-3b-2512",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.1 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "codestral-2508",
		name: "Codestral",
		description:
			"Code specialist model for low-latency code generation and FIM.",
		family: "mistral",
		releasedAt: new Date("2025-07-30"),
		providers: [
			{
				providerId: "mistral",
				modelName: "codestral-2508",
				inputPrice: 0.3 / 1e6,
				outputPrice: 0.9 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "devstral-2512",
		name: "Devstral 2",
		description: "Frontier code agents model for software engineering tasks.",
		family: "mistral",
		releasedAt: new Date("2025-12-09"),
		providers: [
			{
				providerId: "mistral",
				modelName: "devstral-2512",
				inputPrice: 0.4 / 1e6,
				outputPrice: 2 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "devstral-small-2507",
		name: "Devstral Small 1.1",
		description:
			"Compact code model for codebase exploration and multi-file editing.",
		family: "mistral",
		releasedAt: new Date("2025-07-21"),
		providers: [
			{
				providerId: "mistral",
				modelName: "devstral-small-2507",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
