import type { ModelDefinition } from "@/models.js";

export const mistralModels = [
	{
		id: "mistral-large-latest",
		name: "Mistral Large Latest",
		description: "Mistral's flagship large model for complex reasoning tasks.",
		family: "mistral",
		releasedAt: new Date("2024-02-26"),
		publishedAt: new Date("2024-02-26"),
		providers: [
			{
				providerId: "mistral",
				modelName: "mistral-large-latest",
				inputPrice: 0.000004,
				outputPrice: 0.000012,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "mixtral-8x7b-instruct-together",
		name: "Mixtral 8x7B Instruct",
		description: "Mixture-of-experts model with 8x7B architecture.",
		family: "mistral",
		releasedAt: new Date("2023-12-08"),
		publishedAt: new Date("2023-12-08"),
		providers: [
			{
				providerId: "together.ai",
				modelName: "mistralai/mixtral-8x7b-instruct-v0.1",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "mistral-7b-instruct-together",
		name: "Mistral 7B Instruct",
		description: "Compact 7B instruction-tuned Mistral model.",
		family: "mistral",
		releasedAt: new Date("2023-09-27"),
		publishedAt: new Date("2023-09-27"),
		providers: [
			{
				deactivatedAt: new Date("2025-11-13"),
				providerId: "together.ai",
				modelName: "mistralai/mistral-7b-instruct-v0.1",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "pixtral-large-latest",
		name: "Pixtral Large Latest",
		description: "Mistral's multimodal model with vision capabilities.",
		family: "mistral",
		releasedAt: new Date("2024-11-01"),
		publishedAt: new Date("2024-11-01"),
		providers: [
			{
				providerId: "mistral",
				modelName: "pixtral-large-latest",
				inputPrice: 0.000004,
				outputPrice: 0.000012,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: false,
			},
		],
	},
] as const satisfies ModelDefinition[];
