import type { ModelDefinition } from "@/models.js";

export const moonshotModels = [
	{
		id: "kimi-k2",
		name: "Kimi K2",
		description: "Moonshot's Kimi K2 model for general tasks.",
		family: "moonshot",
		releasedAt: new Date("2025-07-11"),
		providers: [
			{
				providerId: "groq",
				modelName: "moonshotai/kimi-k2-instruct",
				// Frequently over capacity on Groq (503)
				// Ref: https://groqstatus.com
				stability: "unstable",
				inputPrice: 1.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				outputPrice: 3.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 16384,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "moonshotai/kimi-k2-instruct",
				// Streaming tool calls produce malformed JSON arguments
				stability: "unstable",
				inputPrice: 0.57 / 1e6,
				outputPrice: 2.3 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 131072,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2-0711-preview",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 128000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2-0905-preview",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 128000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "nebius",
				modelName: "moonshotai/Kimi-K2-Instruct",
				inputPrice: 0.5 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2026-04-25"),
			},
			{
				providerId: "bytedance",
				modelName: "kimi-k2-250905",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.12 / 1e6,
				outputPrice: 2.5 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: 32768,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "Moonshot-Kimi-K2-Instruct",
				inputPrice: 0.574 / 1e6,
				outputPrice: 2.294 / 1e6,
				regions: [{ id: "cn-beijing" }],
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				webSearch: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "kimi-k2-thinking",
		name: "Kimi K2 Thinking",
		description: "Kimi K2 with extended thinking capabilities.",
		family: "moonshot",
		releasedAt: new Date("2025-11-06"),
		providers: [
			{
				providerId: "moonshot",
				modelName: "kimi-k2-thinking",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "bytedance",
				modelName: "kimi-k2-thinking-251104",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.12 / 1e6,
				outputPrice: 2.5 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: 32768,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "kimi-k2-thinking",
				inputPrice: 0.574 / 1e6,
				outputPrice: 2.294 / 1e6,
				regions: [{ id: "cn-beijing" }],
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 16384,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "kimi-k2-thinking-turbo",
		name: "Kimi K2 Thinking Turbo",
		description: "Faster turbo variant of Kimi K2 with extended thinking.",
		family: "moonshot",
		releasedAt: new Date("2025-11-06"),
		providers: [
			{
				providerId: "moonshot",
				modelName: "kimi-k2-thinking-turbo",
				// Frequently overloaded (429 engine_overloaded_error)
				stability: "unstable",
				inputPrice: 1.15 / 1e6,
				outputPrice: 8.0 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "kimi-k2.5",
		name: "Kimi K2.5",
		description:
			"Moonshot's native multimodal model with visual coding and agentic capabilities.",
		family: "moonshot",
		releasedAt: new Date("2026-01-26"),
		providers: [
			{
				providerId: "moonshot",
				modelName: "kimi-k2.5",
				inputPrice: 0.6 / 1e6,
				outputPrice: 3.0 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"max_tokens",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
			{
				providerId: "together-ai",
				modelName: "moonshotai/Kimi-K2.5",
				// Together.ai intermittently returns 500 for this model (~98.7% uptime)
				// Ref: https://status.together.ai
				// Model page: https://www.together.ai/models/kimi-k2-5
				stability: "unstable",
				inputPrice: 0.5 / 1e6,
				outputPrice: 2.8 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "nebius",
				// Streaming tool calls and response_format: json_object are unreliable on Nebius
				stability: "unstable",
				modelName: "moonshotai/Kimi-K2.5",
				inputPrice: 0.5 / 1e6,
				cachedInputPrice: 0.02 / 1e6,
				outputPrice: 2.5 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "kimi-k2.5",
				inputPrice: 0.574 / 1e6,
				outputPrice: 3.011 / 1e6,
				regions: [{ id: "cn-beijing" }],
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 98304,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: false,
			},
			{
				providerId: "embercloud",
				modelName: "kimi-k2.5",
				inputPrice: 0.405 / 1e6,
				outputPrice: 1.98 / 1e6,
				cachedInputPrice: 0.225 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				streaming: true,
				reasoning: false,
				vision: false,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"messages",
					"model",
					"stream",
					"stream_options",
					"temperature",
					"top_p",
					"max_tokens",
					"max_completion_tokens",
					"seed",
					"stop",
					"response_format",
					"tools",
					"tool_choice",
					"parallel_tool_calls",
				],
			},
		],
	},
	{
		id: "kimi-k2.6",
		name: "Kimi K2.6",
		description:
			"Moonshot's latest native multimodal model with long-term code writing, thinking, and agentic capabilities.",
		family: "moonshot",
		releasedAt: new Date("2026-04-20"),
		providers: [
			{
				providerId: "moonshot",
				modelName: "kimi-k2.6",
				inputPrice: 0.95 / 1e6,
				cachedInputPrice: 0.16 / 1e6,
				outputPrice: 4.0 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"max_tokens",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
			{
				providerId: "novita",
				modelName: "moonshotai/kimi-k2.6",
				inputPrice: 0.95 / 1e6,
				cachedInputPrice: 0.16 / 1e6,
				outputPrice: 4.0 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "together-ai",
				modelName: "moonshotai/Kimi-K2.6",
				test: "skip",
				inputPrice: 1.2 / 1e6,
				cachedInputPrice: 0.2 / 1e6,
				outputPrice: 4.5 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: false,
				jsonOutput: false,
			},
		],
	},
] as const satisfies ModelDefinition[];
