import type { ModelDefinition } from "@/models.js";

export const moonshotModels = [
	{
		id: "kimi-k2",
		name: "Kimi K2",
		description: "Moonshot's Kimi K2 model for general tasks.",
		family: "moonshot",
		releasedAt: new Date("2025-07-10"),
		publishedAt: new Date("2025-07-10"),
		providers: [
			{
				providerId: "groq",
				modelName: "moonshotai/kimi-k2-instruct",
				inputPrice: 1.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				outputPrice: 3.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 16384,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "moonshotai/kimi-k2-instruct",
				inputPrice: 0.57 / 1e6,
				outputPrice: 2.3 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 131072,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2-0711-preview",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 128000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "cloudrift",
				modelName: "moonshotai/Kimi-K2-Instruct",
				inputPrice: 0.3 / 1e6,
				outputPrice: 1.75 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 131072,
				streaming: true,
				vision: false,
				tools: true,
				test: "skip",
				jsonOutput: true,
			},
			{
				providerId: "nebius",
				modelName: "moonshotai/Kimi-K2-Instruct",
				inputPrice: 0.5 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "kimi-k2-thinking",
		name: "Kimi K2 Thinking",
		description: "Kimi K2 with extended thinking capabilities.",
		family: "moonshot",
		releasedAt: new Date("2025-07-10"),
		publishedAt: new Date("2025-07-10"),
		providers: [
			{
				providerId: "moonshot",
				modelName: "kimi-k2-thinking",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "canopywave",
				modelName: "moonshotai/kimi-k2-thinking",
				inputPrice: 0.48 / 1e6,
				outputPrice: 2.0 / 1e6,
				discount: 0.75,
				requestPrice: 0,
				contextSize: 262144,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
