import type { ModelDefinition } from "@/models.js";

export const nousresearchModels = [
	{
		id: "hermes-3-llama-405b",
		name: "Hermes 3 Llama 405B",
		description: "Nous Research Hermes 3 based on Llama 405B.",
		family: "nousresearch",
		releasedAt: new Date("2024-08-01"),
		publishedAt: new Date("2024-08-01"),
		providers: [
			{
				providerId: "nebius",
				modelName: "NousResearch/Hermes-3-Llama-3.1-405B",
				inputPrice: 1.0 / 1e6,
				outputPrice: 3.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "hermes-4-405b",
		name: "Hermes 4 405B",
		description: "Nous Research Hermes 4 based on Llama 405B.",
		family: "nousresearch",
		releasedAt: new Date("2025-01-01"),
		publishedAt: new Date("2025-01-01"),
		providers: [
			{
				providerId: "nebius",
				modelName: "NousResearch/Hermes-4-405B",
				inputPrice: 1.0 / 1e6,
				outputPrice: 3.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "hermes-4-70b",
		name: "Hermes 4 70B",
		description: "Nous Research Hermes 4 based on Llama 70B.",
		family: "nousresearch",
		releasedAt: new Date("2025-01-01"),
		publishedAt: new Date("2025-01-01"),
		providers: [
			{
				providerId: "nebius",
				modelName: "NousResearch/Hermes-4-70B",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
