import type { ModelDefinition } from "@/models.js";

export const openaiModels = [
	{
		id: "gpt-4o-mini",
		name: "GPT-4o Mini",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4o-mini",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.075 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4o-mini",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.075 / 1e6,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4",
		name: "GPT-4",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "openai",
				modelName: "gpt-4",
				inputPrice: 30.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4",
				inputPrice: 30.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				contextSize: 8192,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "gpt-4o",
		name: "GPT-4o",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4o",
				inputPrice: 2.5 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 1.25 / 1e6,
				requestPrice: 0,
				imageInputPrice: 0.00553,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4o",
				inputPrice: 2.5 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 1.25 / 1e6,
				imageInputPrice: 0.00553,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-3.5-turbo",
		name: "GPT-3.5 Turbo",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-3.5-turbo",
				inputPrice: 0.5 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 16385,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-35-turbo",
				inputPrice: 0.5 / 1e6,
				outputPrice: 1.5 / 1e6,
				contextSize: 16385,
				maxOutput: 4096,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4-turbo",
		name: "GPT-4 Turbo",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "openai",
				modelName: "gpt-4-turbo",
				inputPrice: 10.0 / 1e6,
				outputPrice: 30.0 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4-turbo",
				inputPrice: 10.0 / 1e6,
				outputPrice: 30.0 / 1e6,
				contextSize: 128000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4.1",
		name: "GPT-4.1",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4.1",
				inputPrice: 2.0 / 1e6,
				outputPrice: 8.0 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4.1",
				inputPrice: 2.0 / 1e6,
				outputPrice: 8.0 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o1",
		name: "o1",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "openai",
				modelName: "o1",
				inputPrice: 15.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				reasoning: true,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "o1",
				inputPrice: 15.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				reasoning: true,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o1-mini",
		name: "o1 Mini",
		family: "openai",
		providers: [
			{
				stability: "unstable" as const,
				providerId: "openai",
				modelName: "o1-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: false,
				vision: false,
				tools: false,
				reasoning: false,
				supportsResponsesApi: false,
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "o1-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: false,
				vision: false,
				tools: false,
				reasoning: false,
				supportsResponsesApi: false,
				jsonOutput: false,
			},
		],
		supportsSystemRole: false,
	},
	{
		id: "gpt-4.1-mini",
		name: "GPT-4.1 Mini",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4.1-mini",
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.6 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4.1-mini",
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.6 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4.1-nano",
		name: "GPT-4.1 Nano",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4.1-nano",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4.1-nano",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o3",
		name: "o3",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "o3",
				inputPrice: 2 / 1e6,
				outputPrice: 8 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: false,
				vision: true,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "o3",
				inputPrice: 2 / 1e6,
				outputPrice: 8 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: false,
				vision: true,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o3-mini",
		name: "o3 Mini",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "o3-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "o3-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-oss-120b",
		name: "GPT OSS 120B",
		family: "openai",
		providers: [
			{
				providerId: "groq",
				modelName: "openai/gpt-oss-120b",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.75 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "nanogpt",
				modelName: "openai/gpt-oss-120b",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.25 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-oss-20b",
		name: "GPT OSS 20B",
		family: "openai",
		providers: [
			{
				providerId: "groq",
				modelName: "openai/gpt-oss-20b",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "nanogpt",
				modelName: "openai/gpt-oss-20b",
				inputPrice: 0.04 / 1e6,
				outputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5",
		name: "GPT-5",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "routeway-discount",
				modelName: "gpt-5",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				discount: 0.5,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: true,
				tools: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-mini",
		name: "GPT-5 Mini",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5-mini",
				inputPrice: 0.25 / 1e6,
				outputPrice: 2 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				providerId: "routeway-discount",
				modelName: "gpt-5-mini",
				inputPrice: 0.25 / 1e6,
				outputPrice: 2 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				discount: 0.5,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: true,
				tools: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5-mini",
				inputPrice: 0.25 / 1e6,
				outputPrice: 2 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-nano",
		name: "GPT-5 Nano",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5-nano",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.005 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				providerId: "routeway-discount",
				modelName: "gpt-5-nano",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.005 / 1e6,
				discount: 0.5,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5-nano",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.005 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-chat-latest",
		name: "GPT-5 Chat Latest",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5-chat-latest",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.1",
		name: "GPT-5.1",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.1",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				reasoning: true,
				reasoningOutput: "omit",
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-pro",
		name: "GPT-5 Pro",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "openai",
				modelName: "gpt-5-pro",
				inputPrice: 15 / 1e6,
				outputPrice: 120.0 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 272000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.1-codex",
		name: "GPT-5.1 Codex",
		family: "openai",
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.1-codex",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 272000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
