import type { ModelDefinition } from "@/models.js";

export const perplexityModels = [
	{
		id: "sonar-reasoning-pro",
		name: "Sonar Reasoning Pro",
		family: "perplexity",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "perplexity",
				modelName: "sonar-reasoning-pro",
				inputPrice: 2 / 1e6,
				outputPrice: 8 / 1e6,
				requestPrice: 5.0 / 1000,
				imageInputPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				test: "skip",
			},
		],
		jsonOutput: false,
	},
	{
		id: "sonar-pro",
		name: "Sonar Pro",
		family: "perplexity",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "perplexity",
				modelName: "sonar-pro",
				inputPrice: 3 / 1e6,
				outputPrice: 15 / 1e6,
				requestPrice: 5.0 / 1000,
				imageInputPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				test: "skip",
			},
		],
		jsonOutput: false,
	},
	{
		id: "sonar",
		name: "Sonar",
		family: "perplexity",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "perplexity",
				modelName: "sonar",
				inputPrice: 1 / 1e6,
				outputPrice: 1 / 1e6,
				requestPrice: 5.0 / 1000,
				imageInputPrice: 0,
				contextSize: 130000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				test: "skip",
			},
		],
		jsonOutput: false,
	},
] as const satisfies ModelDefinition[];
