import type { ModelDefinition } from "@/models.js";

/**
 * Apply discount to Routeway paid models based on ROUTEWAY_PAID_DISCOUNT env var
 */
function getDiscountedPrice(basePrice: number): number {
	const discount = parseFloat(process.env.ROUTEWAY_PAID_DISCOUNT || "1");
	return basePrice * discount;
}

export const routewayModels = [
	{
		id: "deepseek-r1t2-chimera-free",
		name: "DeepSeek R1T2 Chimera (Free)",
		family: "deepseek",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "routeway",
				modelName: "deepseek-r1t2-chimera:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 163840,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "glm-4.5-air-free",
		name: "GLM-4.5 Air (Free)",
		family: "glm",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "routeway",
				modelName: "glm-4.5-air:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "kimi-k2-free",
		name: "Kimi K2 (Free)",
		family: "kimi",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "routeway",
				modelName: "kimi-k2:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-oss-20b-free",
		name: "GPT OSS 20B (Free)",
		family: "gpt-oss",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "routeway",
				modelName: "gpt-oss-20b:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-4.1-free",
		name: "GPT-4.1 (Free)",
		family: "openai",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "routeway",
				modelName: "gpt-4.1:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 1047576,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "llama-3.3-70b-instruct-free",
		name: "Meta Llama 3.3 70B Instruct (Free)",
		family: "meta",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "routeway",
				modelName: "llama-3.3-70b-instruct:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "llama-4-scout-free",
		name: "Meta Llama 4 Scout (Free)",
		family: "meta",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "routeway",
				modelName: "llama-4-scout:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 1_000_000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "llama-4-maverick-free",
		name: "Meta Llama 4 Maverick (Free)",
		family: "meta",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "routeway",
				modelName: "llama-4-maverick:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 1_000_000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "nemotron-nano-9b-v2",
		name: "Nemotron Nano 9B V2",
		family: "nvidia",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "routeway",
				modelName: "nemotron-nano-9b-v2:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 128_000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "claude-opus-4-20250514-v1:0",
		name: "Claude Opus 4 (2025-05-14) v1:0",
		family: "anthropic",
		free: false,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "only",
				providerId: "routeway-discount",
				modelName: "claude-opus-4-20250514-v1:0",
				inputPrice: getDiscountedPrice(15.0) / 1e6,
				outputPrice: getDiscountedPrice(75.0) / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "claude-opus-4-1-20250805-v1:0",
		name: "Claude Opus 4.1 (2025-08-05) v1:0",
		family: "anthropic",
		free: false,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "only",
				providerId: "routeway-discount",
				modelName: "claude-opus-4-1-20250805-v1:0",
				inputPrice: getDiscountedPrice(15.0) / 1e6,
				outputPrice: getDiscountedPrice(75.0) / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				reasoning: true,
				reasoningOutput: "omit",
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "claude-3-7-sonnet-20250219-v1:0",
		name: "Claude 3.7 Sonnet (2025-02-19) v1:0",
		family: "anthropic",
		free: false,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "only",
				providerId: "routeway-discount",
				modelName: "claude-3-7-sonnet-20250219-v1:0",
				inputPrice: getDiscountedPrice(3.0) / 1e6,
				outputPrice: getDiscountedPrice(15.0) / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				reasoning: true,
				reasoningOutput: "omit",
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "claude-3-5-haiku-20241022-v1:0",
		name: "Claude 3.5 Haiku (2024-10-22) v1:0",
		family: "anthropic",
		free: false,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "only",
				providerId: "routeway-discount",
				modelName: "claude-3-5-haiku-20241022-v1:0",
				inputPrice: getDiscountedPrice(0.8) / 1e6,
				outputPrice: getDiscountedPrice(4.0) / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "claude-sonnet-4-20250514-v1:0",
		name: "Claude Sonnet 4 (2025-05-14) v1:0",
		family: "anthropic",
		free: false,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				test: "only",
				providerId: "routeway-discount",
				modelName: "claude-sonnet-4-20250514-v1:0",
				inputPrice: getDiscountedPrice(3.0) / 1e6,
				outputPrice: getDiscountedPrice(15.0) / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
] as const satisfies ModelDefinition[];
