import type { ModelDefinition } from "@/models.js";

export const routewayModels = [
	{
		id: "deepseek-r1t2-chimera-free",
		name: "DeepSeek R1T2 Chimera (Free)",
		description: "Free DeepSeek R1T2 Chimera for testing.",
		family: "deepseek",
		free: true,
		providers: [
			{
				providerId: "routeway",
				stability: "unstable" as const,
				modelName: "deepseek-r1t2-chimera:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 163840,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5-air-free",
		name: "GLM-4.5 Air (Free)",
		description: "Free GLM-4.5 Air model.",
		family: "glm",
		free: true,
		providers: [
			{
				providerId: "routeway",
				stability: "unstable" as const,
				modelName: "glm-4.5-air:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "kimi-dev-72b-free",
		name: "Kimi Dev 72B (Free)",
		description: "Free Kimi Dev 72B for development.",
		family: "kimi",
		free: true,
		providers: [
			{
				providerId: "routeway",
				stability: "unstable" as const,
				modelName: "kimi-dev-72b:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 131000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "mistral-small-3-free",
		name: "Mistral Small 3 (Free)",
		description: "Free Mistral Small 3.",
		family: "mistral",
		free: true,
		providers: [
			{
				providerId: "routeway",
				stability: "unstable" as const,
				modelName: "mistral-small-3:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 32000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-oss-20b-free",
		name: "GPT OSS 20B (Free)",
		description: "Free GPT OSS 20B model.",
		family: "gpt-oss",
		free: true,
		providers: [
			{
				providerId: "routeway",
				stability: "unstable" as const,
				modelName: "gpt-oss-20b:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "llama-3.3-70b-instruct-free",
		name: "Meta Llama 3.3 70B Instruct (Free)",
		description: "Free Llama 3.3 70B.",
		family: "meta",
		free: true,
		providers: [
			{
				providerId: "routeway",
				stability: "unstable" as const,
				modelName: "llama-3.3-70b-instruct:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "llama-4-scout-free",
		name: "Meta Llama 4 Scout (Free)",
		description: "Free Llama 4 Scout.",
		family: "meta",
		free: true,
		providers: [
			{
				providerId: "routeway",
				stability: "unstable" as const,
				modelName: "llama-4-scout:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 1_000_000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "llama-4-maverick-free",
		name: "Meta Llama 4 Maverick (Free)",
		description: "Free Llama 4 Maverick.",
		family: "meta",
		free: true,
		providers: [
			{
				providerId: "routeway",
				stability: "unstable" as const,
				modelName: "llama-4-maverick:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 1_000_000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "nemotron-nano-9b-v2",
		name: "Nemotron Nano 9B V2 (Free)",
		description: "Free NVIDIA Nemotron Nano 9B.",
		family: "nvidia",
		free: true,
		providers: [
			{
				providerId: "routeway",
				stability: "unstable" as const,
				modelName: "nemotron-nano-9b-v2:free",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 128_000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
