import type { ModelDefinition } from "@/models.js";

export const thinkingmachinesModels = [
	{
		id: "inkling",
		name: "Inkling",
		description:
			"Thinking Machines Lab's open-weight multimodal MoE model (975B total, 41B active) for reasoning, coding, and agentic tool use.",
		family: "thinkingmachines",
		releasedAt: new Date("2026-07-18"),
		providers: [
			{
				providerId: "together-ai",
				externalId: "thinkingmachines/Inkling",
				inputPrice: "1e-6",
				cachedInputPrice: "0.17e-6",
				outputPrice: "4.05e-6",
				requestPrice: "0",
				contextSize: 524288,
				maxOutput: 471859,
				quantization: "fp8",
				streaming: true,
				reasoning: true,
				reasoningEfforts: [
					"none",
					"minimal",
					"low",
					"medium",
					"high",
					"xhigh",
					"max",
				],
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "deepinfra",
				externalId: "thinkingmachines/Inkling",
				inputPrice: "0.95e-6",
				cachedInputPrice: "0.16e-6",
				outputPrice: "4.05e-6",
				requestPrice: "0",
				contextSize: 524288,
				maxOutput: 262144,
				quantization: "fp8",
				maxTemperature: 1,
				streaming: true,
				reasoning: true,
				reasoningEfforts: [
					"none",
					"minimal",
					"low",
					"medium",
					"high",
					"xhigh",
					"max",
				],
				vision: true,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "inkling-small",
		name: "Inkling Small",
		description:
			"Smaller, more efficient member of Thinking Machines Lab's open-weight multimodal Inkling family (276B total, 12B active).",
		family: "thinkingmachines",
		releasedAt: new Date("2026-07-31"),
		providers: [
			{
				providerId: "deepinfra",
				externalId: "thinkingmachines/Inkling-Small",
				inputPrice: "0.45e-6",
				cachedInputPrice: "0.1e-6",
				outputPrice: "1.2e-6",
				requestPrice: "0",
				contextSize: 524288,
				maxOutput: 262144,
				quantization: "fp8",
				streaming: true,
				reasoning: true,
				reasoningEfforts: [
					"none",
					"minimal",
					"low",
					"medium",
					"high",
					"xhigh",
					"max",
				],
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
