import type { ModelDefinition } from "@/models.js";

export const zaiModels = [
	{
		id: "glm-4.5",
		name: "GLM-4.5",
		description: "Zhipu GLM-4.5 with reasoning capabilities.",
		family: "glm",
		releasedAt: new Date("2024-05-06"),
		publishedAt: new Date("2024-05-06"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.2 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5v",
		name: "GLM-4.5V",
		description: "GLM-4.5 with vision support.",
		family: "glm",
		releasedAt: new Date("2024-05-06"),
		publishedAt: new Date("2024-05-06"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5v",
				inputPrice: 0.6 / 1e6,
				outputPrice: 1.8 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5-air",
		name: "GLM-4.5 Air",
		description: "Lightweight GLM-4.5 variant.",
		family: "glm",
		releasedAt: new Date("2024-05-06"),
		publishedAt: new Date("2024-05-06"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-air",
				inputPrice: 0.2 / 1e6,
				outputPrice: 1.1 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: false,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5-x",
		name: "GLM-4.5 X",
		description: "Extended GLM-4.5 with advanced reasoning.",
		family: "glm",
		releasedAt: new Date("2024-05-06"),
		publishedAt: new Date("2024-05-06"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-x",
				inputPrice: 2.2 / 1e6,
				outputPrice: 8.9 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				stability: "unstable", // unstable due to high limits
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5-airx",
		name: "GLM-4.5 AirX",
		description: "Enhanced GLM-4.5 Air variant.",
		family: "glm",
		releasedAt: new Date("2024-05-06"),
		publishedAt: new Date("2024-05-06"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-airx",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.5 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: false,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5-flash",
		name: "GLM-4.5 Flash",
		description: "Free, fast GLM-4.5 model.",
		family: "glm",
		free: true,
		releasedAt: new Date("2024-05-06"),
		publishedAt: new Date("2024-05-06"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-flash",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: false,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.6",
		name: "GLM-4.6",
		description: "Updated GLM with reasoning capabilities.",
		family: "glm",
		releasedAt: new Date("2025-06-01"),
		publishedAt: new Date("2025-06-01"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.6",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.2 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "canopywave",
				modelName: "zai/glm-4.6",
				inputPrice: 0.45 / 1e6,
				outputPrice: 1.5 / 1e6,
				discount: 0.75,
				requestPrice: 0,
				contextSize: 202752,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4-32b-0414-128k",
		name: "GLM-4 32B (0414-128k)",
		description: "GLM-4 32B instruction-tuned model.",
		family: "glm",
		releasedAt: new Date("2024-04-14"),
		publishedAt: new Date("2024-04-14"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4-32b-0414-128k",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.1 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: false,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
